(function(){
  "use strict";
  const html=value=>typeof esc==="function"?esc(value):String(value||"").replace(/[&<>"']/g,s=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[s]));
  const fileSafe=value=>String(value||"yks").toLocaleLowerCase("tr").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,50)||"yks";
  function saveFile(name,content,type="text/plain;charset=utf-8",bom=true){const blob=new Blob([bom?"\ufeff":"",content],{type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);return blob;}
  function dayStats(days=30){let questions=0,minutes=0,active=0;for(let i=0;i<days;i++){const key=addDaysKey(todayKey(),-i),q=Number(S.solved[key])||0,m=Number(S.pomoMin[key])||0;questions+=q;minutes+=m;if(q||m)active++;}return {questions,minutes,active};}
  function recentExams(limit=10){return S.denemeler.slice().sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id).slice(0,limit);}
  function topicSummary(){let tracked=0,done=0,reviews=0;Object.values(S.topics||{}).forEach(x=>{if(!x)return;if(x.st||x.conf)tracked++;if(x.st===3)done++;reviews+=(x.rev||[]).length;});return {tracked,done,reviews};}
  function reportData(){const stats=dayStats(30),topics=topicSummary(),scores=typeof estScores==="function"?estScores():{},rank=scores.alan&&typeof rankEstimate==="function"?rankEstimate(scores.alan):null;return {stats,topics,scores,rank,exams:recentExams(10),targets:Array.isArray(S.targets)?S.targets:[],cards:S.learning?.cards||[]};}
  function buildMarkdown(){const d=reportData(),lines=["# YKS Defterim — Çalışma Özeti","",`- Tarih: ${new Date().toLocaleDateString("tr-TR")}`,`- Öğrenci: ${S.name||"Belirtilmedi"}`,`- Sınav tarihi: ${S.examDate||"—"}`,"","## Son 30 gün","",`- Çalışma: ${Math.floor(d.stats.minutes/60)} sa ${d.stats.minutes%60} dk`,`- Soru: ${d.stats.questions}`,`- Aktif gün: ${d.stats.active}`,`- Tamamlanan konu: ${d.topics.done}`,`- Yapılan konu tekrarı: ${d.topics.reviews}`,"","## Puan ve hedef","",`- TYT net ortalaması: ${d.scores.tytNet??"—"}`,`- Alan net ortalaması: ${(S.puanTuru==="DIL"?d.scores.ydtNet:d.scores.aytNet)??"—"}`,`- Tahmini ${S.puanTuru} puanı: ${d.scores.alan??d.scores.tyt??"—"}`,`- Tahmini sıra aralığı: ${d.rank?d.rank.best.toLocaleString("tr-TR")+" – "+d.rank.worst.toLocaleString("tr-TR"):"—"}`,"","## Son denemeler","","| Tarih | Tür | Deneme | Net |","|---|---|---|---:|",...d.exams.map(x=>`| ${x.date} | ${x.type} | ${String(x.name||"Deneme").replace(/\|/g,"/")} | ${x.totalNet} |`),"","## Hedef bölümler","",...(d.targets.length?d.targets.map(x=>`- ${x.ad}${x.uni?" — "+x.uni:""}: ${Number(x.sira).toLocaleString("tr-TR")}`):["- Henüz hedef bölüm eklenmedi."]),"","## Tekrar kartları","",`Toplam ${d.cards.length} kart; bugün bekleyen ${(d.cards.filter(x=>(x.due||todayKey())<=todayKey())).length} kart.`,""];return lines.join("\n");}
  function planEvents(){const events=[];Object.entries(S.weeks||{}).forEach(([weekKey,week])=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(weekKey)||!week)return;["r","s"].forEach(block=>(Array.isArray(week[block])?week[block]:[]).forEach((row,rowIndex)=>(Array.isArray(row)?row:[]).slice(0,7).forEach((text,day)=>{const title=String(text||"").trim();if(!title)return;const date=addDaysKey(weekKey,day);if(date<addDaysKey(todayKey(),-7)||date>addDaysKey(todayKey(),180))return;events.push({date,title,kind:block==="r"?"Rutin":"Çalışma",row:rowIndex});})));});return events.sort((a,b)=>a.date.localeCompare(b.date));}
  const icsText=value=>String(value||"").replace(/\\/g,"\\\\").replace(/;/g,"\\;").replace(/,/g,"\\,").replace(/\n/g,"\\n");
  const compactDate=value=>String(value).replace(/-/g,"");
  function buildICS(){const events=planEvents(),lines=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//YKS Defterim//TR","CALSCALE:GREGORIAN","METHOD:PUBLISH","X-WR-CALNAME:YKS Defterim Planı"];events.forEach((x,i)=>{lines.push("BEGIN:VEVENT",`UID:${compactDate(x.date)}-${i}-${fileSafe(x.title)}@yks-defterim`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,"").replace(/\.\d{3}/,"")}`,`DTSTART;VALUE=DATE:${compactDate(x.date)}`,`DTEND;VALUE=DATE:${compactDate(addDaysKey(x.date,1))}`,`SUMMARY:${icsText(x.title)}`,`DESCRIPTION:${icsText(x.kind+" planı · YKS Defterim")}`,"END:VEVENT");});lines.push("END:VCALENDAR");return {text:lines.join("\r\n"),count:events.length};}
  function buildAnki(){const cards=S.learning?.cards||[],rows=cards.map(x=>[x.q,x.a,"YKS_Defterim "+String(x.subject||"Genel").replace(/\s+/g,"_")].map(v=>String(v||"").replace(/[\t\r\n]+/g," ")).join("\t"));return {text:"#separator:tab\n#html:false\n#tags column:3\n"+rows.join("\n"),count:cards.length};}
  function printReport(){const d=reportData(),w=window.open("","_blank");if(!w){toast("Rapor penceresi engellendi; açılır pencereye izin ver");return false;}try{w.opener=null;}catch(e){}const examRows=d.exams.map(x=>`<tr><td>${html(x.date)}</td><td>${html(x.type)}</td><td>${html(x.name)}</td><td>${x.totalNet}</td></tr>`).join("")||'<tr><td colspan="4">Deneme kaydı yok</td></tr>';const targetRows=d.targets.map(x=>`<li>${html(x.ad)}${x.uni?" · "+html(x.uni):""} — ${Number(x.sira).toLocaleString("tr-TR")}</li>`).join("")||"<li>Hedef bölüm eklenmedi</li>";w.document.write(`<!doctype html><html lang="tr"><head><meta charset="utf-8"><title>YKS Defterim Raporu</title><style>body{font-family:Arial,sans-serif;color:#17202a;margin:38px;line-height:1.5}h1{margin-bottom:4px}small{color:#667085}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:22px 0}.k{padding:15px;border:1px solid #dfe3e8;border-radius:12px}.k b,.k span{display:block}.k b{font-size:22px}.k span{font-size:11px;color:#667085}table{width:100%;border-collapse:collapse}th,td{border-bottom:1px solid #e5e7eb;padding:8px;text-align:left}footer{margin-top:28px;font-size:10px;color:#777}@media print{body{margin:18mm}.no-print{display:none}}</style></head><body><button class="no-print" onclick="print()">Yazdır / PDF kaydet</button><h1>YKS Defterim</h1><small>${html(S.name||"Öğrenci")} · ${new Date().toLocaleDateString("tr-TR")} · v${html(APP_VERSION)}</small><div class="grid"><div class="k"><b>${d.stats.questions}</b><span>30 günde soru</span></div><div class="k"><b>${Math.floor(d.stats.minutes/60)} sa</b><span>30 günde odak</span></div><div class="k"><b>${d.topics.done}</b><span>tamamlanan konu</span></div><div class="k"><b>${d.scores.alan??d.scores.tyt??"—"}</b><span>tahmini puan</span></div></div><h2>Son denemeler</h2><table><thead><tr><th>Tarih</th><th>Tür</th><th>Deneme</th><th>Net</th></tr></thead><tbody>${examRows}</tbody></table><h2>Hedef bölümler</h2><ul>${targetRows}</ul><h2>Öğrenme</h2><p>${d.cards.length} tekrar kartı · ${d.topics.reviews} konu tekrarı · ${d.topics.tracked} izlenen konu.</p><footer>Puan ve sıralama değerleri yaklaşık yön göstergesidir; resmî sonuç değildir.</footer><script>setTimeout(()=>print(),350)<\/script></body></html>`);w.document.close();return true;}
  function rounded(ctx,x,y,w,h,r){ctx.beginPath();if(typeof ctx.roundRect==="function")ctx.roundRect(x,y,w,h,r);else{ctx.moveTo(x+r,y);ctx.lineTo(x+w-r,y);ctx.quadraticCurveTo(x+w,y,x+w,y+r);ctx.lineTo(x+w,y+h-r);ctx.quadraticCurveTo(x+w,y+h,x+w-r,y+h);ctx.lineTo(x+r,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-r);ctx.lineTo(x,y+r);ctx.quadraticCurveTo(x,y,x+r,y);}ctx.fill();}
  async function shareCard(){const d=reportData(),canvas=document.createElement("canvas");canvas.width=1080;canvas.height=1920;const c=canvas.getContext("2d"),g=c.createLinearGradient(0,0,1080,1920);g.addColorStop(0,"#12263f");g.addColorStop(.5,"#1c4f63");g.addColorStop(1,"#d08a36");c.fillStyle=g;c.fillRect(0,0,1080,1920);c.fillStyle="rgba(255,255,255,.10)";for(let i=0;i<16;i++){c.beginPath();c.arc((i*173)%1100,(i*277)%1900,70+(i%4)*45,0,Math.PI*2);c.fill();}c.fillStyle="#fff";c.font="700 42px Arial";c.fillText("YKS DEFTERİM",74,108);c.font="800 74px Arial";c.fillText("Bu ayın emeği",74,220);c.font="400 30px Arial";c.fillStyle="rgba(255,255,255,.78)";c.fillText((S.name||"Öğrenci")+" · "+new Date().toLocaleDateString("tr-TR"),74,278);const cards=[[d.stats.questions,"soru"],[Math.floor(d.stats.minutes/60)+" sa","odak"],[d.stats.active,"aktif gün"],[d.topics.done,"tamamlanan konu"]];cards.forEach((x,i)=>{const col=i%2,row=Math.floor(i/2),px=74+col*474,py=380+row*240;c.fillStyle="rgba(255,255,255,.14)";rounded(c,px,py,430,190,28);c.fillStyle="#fff";c.font="800 62px Arial";c.fillText(String(x[0]),px+28,py+82);c.font="500 25px Arial";c.fillStyle="rgba(255,255,255,.78)";c.fillText(x[1],px+28,py+132);});c.fillStyle="rgba(255,255,255,.14)";rounded(c,74,900,904,600,30);c.fillStyle="#fff";c.font="700 34px Arial";c.fillText("SON DENEMELER",110,970);c.font="500 29px Arial";(d.exams.slice(0,6)).forEach((x,i)=>{c.fillStyle="rgba(255,255,255,.78)";c.fillText((x.date||"")+" · "+String(x.name||"Deneme").slice(0,32),110,1045+i*70);c.fillStyle="#fff";c.font="800 31px Arial";c.textAlign="right";c.fillText(String(x.totalNet)+" net",930,1045+i*70);c.textAlign="left";c.font="500 29px Arial";});c.fillStyle="#fff";c.font="800 38px Arial";c.fillText("Her gün biraz daha ileri.",74,1670);c.font="400 24px Arial";c.fillStyle="rgba(255,255,255,.72)";c.fillText("Kişisel notlar ve günlük içerikleri bu karta eklenmez.",74,1720);const blob=await new Promise(resolve=>canvas.toBlob(resolve,"image/png",.96));if(!blob){toast("Kart hazırlanamadı");return false;}const file=new File([blob],"yks-calisma-karti-"+todayKey()+".png",{type:"image/png"});if(navigator.share&&navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],title:"YKS Defterim çalışma kartı"});return true;}catch(e){if(e?.name==="AbortError")return false;}}const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);toast("Çalışma kartı indirildi ✓");return true;}
  function render(){const root=document.getElementById("v322ExportSummary");if(!root)return false;const plan=planEvents().length,cards=S.learning?.cards?.length||0;root.textContent=plan+" plan · "+cards+" kart";return true;}
  window.v322PrintReport=printReport;window.v322ExportICS=()=>{const out=buildICS();if(!out.count){toast("Takvime aktarılacak dolu plan yok");return false;}saveFile("yks-plani-"+todayKey()+".ics",out.text,"text/calendar;charset=utf-8",false);toast(out.count+" plan takvime hazırlandı ✓");return true;};window.v322ExportAnki=()=>{const out=buildAnki();if(!out.count){toast("Dışa aktarılacak tekrar kartı yok");return false;}saveFile("yks-anki-kartlari-"+todayKey()+".txt",out.text);toast(out.count+" kart Anki dosyasına yazıldı ✓");return true;};window.v322ExportObsidian=()=>{saveFile("yks-defterim-"+todayKey()+".md",buildMarkdown(),"text/markdown;charset=utf-8");toast("Obsidian notu indirildi ✓");return true;};window.v322ShareCard=shareCard;window.v322RenderExportCenter=render;window.YKSExportCenter={buildICS,buildAnki,buildMarkdown,planEvents,reportData};
  const oldMore=window.setMoreTab;if(typeof oldMore==="function")window.setMoreTab=function(){const result=oldMore.apply(this,arguments);if(arguments[0]==="veri")setTimeout(render,0);return result;};if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>setTimeout(render,420),{once:true});else setTimeout(render,420);
})();
