(function(){
  "use strict";

  const SOURCES={
    mebTests:{label:"MEB Kazanım Testleri",url:"https://odsgm.meb.gov.tr/www/kazanim-testleri/kategori/107"},
    mebYks:{label:"MEB TYT–AYT–YDT Çalışma Soruları",url:"https://odsgm.meb.gov.tr/www/yuksekogretim-kurumlari-sinavi039na-yonelik-temel-yeterlilik-testi-tyt-alan-yeterlilik-testi-ayt-ve-yabanci-dil-testi-ydt-calisma-sorulari-mart-2022/icerik/804"},
    osym:{label:"ÖSYM YKS Çıkmış Soruları",url:"https://www.osym.gov.tr/SinavGrubu/Menu/323"},
    ogm:{label:"OGM YKS Hazırlık",url:"https://ogmmateryal.eba.gov.tr/YKSHazirlik"}
  };

  const PROFILES={
    turkce:{subjects:["Türkçe"],important:"Soruyu kök, bağlam ve seçenek ilişkisiyle çöz; yalnızca ezberlenmiş tanıma dayanma.",attention:"Olumsuz soru köklerini ve kesinlik bildiren sözcükleri işaretle.",mistake:"Metinde olmayan bir yorumu doğru kabul etmek.",study:"Önce kısa konu özeti çıkar, ardından süre tutmadan 15; süreli 20 soru çöz. Yanlışta yalnız cevabı değil, seni yanıltan ifadeyi de yaz."},
    math:{subjects:["Matematik","Matematik (AYT)"],important:"Tanım kümesi, işaret, birim ve özel durum kontrolünü işlemin başında yap.",attention:"Ezber formülü kullanmadan önce verilenlerin formülün koşullarını sağladığını doğrula.",mistake:"Ara işlemi doğru yapıp koşul veya sonuç kümesi kontrolünü atlamak.",study:"Kavramı bir örnekle kur, 5 temel–10 orta–5 yeni nesil soru çöz; yanlış soruyu çözümüne bakmadan ertesi gün yeniden dene."},
    geometry:{subjects:["Geometri","Geometri (AYT)"],important:"Şekli verilen bilgiye göre yeniden çiz; eşitlikleri, paralellikleri ve diklikleri şekil üzerinde işaretle.",attention:"Ölçeksiz çizilmiş şekilden uzunluk veya açı ilişkisi tahmin etme.",mistake:"Gizli yardımcı çizgiyi aramadan doğrudan formül denemek.",study:"Önce 3 temel çizim yap, sonra aynı kazanımı farklı şekillerde soran 15 soru çöz; her çözümde kullandığın teoremi adlandır."},
    physics:{subjects:["Fizik","Fizik (AYT)"],important:"Büyüklüğün skaler mi vektörel mi olduğunu, yönü ve birimi her adımda koru.",attention:"Grafiklerde eğim ile alanın hangi fiziksel büyüklüğü verdiğini karıştırma.",mistake:"Formülü ezberleyip sistem sınırlarını ve işaret seçimini belirtmemek.",study:"Kavram şemasından sonra birim analizi yap; 5 yorum, 10 işlem ve 5 grafik sorusuyla konuyu tamamla."},
    chemistry:{subjects:["Kimya","Kimya (AYT)"],important:"Tanecik düzeyi, mol düzeyi ve gözlenebilir olay düzeyini birbirinden ayır.",attention:"Denklem, yük, atom sayısı, birim ve hâl sembollerini birlikte kontrol et.",mistake:"Benzer görünen kavramları—örneğin güçlü/derişik veya hız/denge—aynı sanmak.",study:"Kavram tablosu çıkar, birimleriyle 15 hesaplama/yorum sorusu çöz ve yanlış kavram çiftlerini karşılaştırma kartına dönüştür."},
    biology:{subjects:["Biyoloji","Biyoloji (AYT)"],important:"Yapı–görev–yer ilişkisini ve olayların sırasını birlikte öğren.",attention:"Her canlıda gerçekleşen olaylarla yalnız belirli hücre veya organlarda gerçekleşenleri ayır.",mistake:"Şemadaki ok yönünü ya da artar–azalır ilişkisini ters okumak.",study:"Konuyu tek sayfalık şema hâline getir; ardından 10 bilgi, 10 deney/yorum sorusu çöz ve karıştırdığın terimleri karşılaştır."},
    history:{subjects:["Tarih","Tarih (AYT)","Tarih-2"],important:"Olayı tarih, neden, gelişme ve sonuç zinciri içinde değerlendir.",attention:"Aynı dönemdeki iç gelişmelerle dış gelişmeleri birbirine karıştırma.",mistake:"Tek bir olaydan dönem için aşırı genel sonuç çıkarmak.",study:"Kısa kronoloji ve neden–sonuç tablosu hazırla; 20 sorudan sonra yanlış seçeneklerin hangi dönemle ilgili olduğunu not et."},
    geography:{subjects:["Coğrafya","Coğrafya (AYT)","Coğrafya-2"],important:"Dağılış, neden ve sonuç ilişkisini harita üzerinde birlikte düşün.",attention:"Dünya geneli ile Türkiye'ye özgü koşulları birbirine taşımamaya dikkat et.",mistake:"Harita ölçeği, yön, yükselti veya konum bilgisini okumadan yorum yapmak.",study:"Boş harita üzerinde kavramı yerleştir; 10 harita/grafik ve 10 neden–sonuç sorusuyla pekiştir."},
    philosophy:{subjects:["Felsefe","Felsefe Grubu"],important:"Görüşü filozof adından önce temel problem, sav ve gerekçesiyle tanı.",attention:"Günlük dilde yakın duran kavramların felsefi anlamlarını ayır.",mistake:"Parçada savunulan görüş yerine kendi kişisel görüşünü işaretlemek.",study:"Kavram–soru–yaklaşım tablosu çıkar; kısa paragraflarda ana savı tek cümleyle yazıp 15 yorum sorusu çöz."},
    religion:{subjects:["Din Kültürü","Din Kültürü (AYT)"],important:"Kavramları ayet/hadis bağlamı, amaç ve günlük hayata yansımasıyla birlikte değerlendir.",attention:"Dinî hüküm, yorum ve kültürel uygulama arasındaki farkı koru.",mistake:"Parçanın verdiği ölçüt yerine ezber bir ifadeyle sonuca gitmek.",study:"Kavramları anlam–örnek–karşı kavram biçiminde çalış; ardından 15 paragraf/yorum sorusu çöz."},
    literature:{subjects:["Edebiyat"],important:"Dönem, sanatçı, eser, tür ve anlayış bağlarını birlikte kur.",attention:"Benzer dönemleri yalnız tarihleriyle değil dil, tema ve sanat anlayışıyla ayır.",mistake:"Bir sanatçıyı tek eseri üzerinden yanlış döneme yerleştirmek.",study:"Dönem karşılaştırma tablosu ve sanatçı–eser kartları hazırla; her gün 20 karma bilgi/yorum sorusu çöz."},
    ydt:{subjects:["Yabancı Dil"],important:"Cümlenin anlam akışını; bağlaç, zaman, zamir ve anahtar sözcüklerle birlikte izle.",attention:"Yalnız tek sözcük eşleşmesine dayanma; seçeneğin tüm cümle/paragrafla uyumunu denetle.",mistake:"Dil bilgisi doğru görünen ama bağlama uymayan seçeneği işaretlemek.",study:"Konu tekniğini 5 örnekte uygula, ardından süreli 20 soru çöz; yanlışta bilinmeyen sözcükten önce bağlam ipucunu kaydet."}
  };

  const NOTES={
    /* Türkçe */
    "Sözcükte Anlam":["Gerçek, mecaz, terim ve yan anlamı sözcüğün cümlede kazandığı anlamla ayır.","Yakın anlamlı sözcüklerin her bağlamda birbirinin yerine geçmeyeceğini unutma.","Altı çizili sözcüğü cümleden koparıp yalnız sözlük anlamıyla yorumlamak."],
    "Cümlede Anlam":["Neden–sonuç, amaç–sonuç, koşul, varsayım, olasılık ve çıkarım ilişkilerini yüklem ve bağlaçlardan izle.","Öznel–nesnel ayrımında cümlenin kanıtlanabilir olup olmadığını ölçüt al.","Gerekçe bildiren her cümleyi amaç–sonuç sanmak."],
    "Paragraf":["Ana düşünce bütün paragrafı kapsar; yardımcı düşünceler ana düşünceyi açıklar veya destekler.","Soru kökündeki “değinilmemiştir”, “çıkarılamaz” gibi olumsuz ifadeleri görünür biçimde işaretle.","Seçenekte doğru bir bilgi gördüğü için metinde karşılığı olmadan işaretlemek."],
    "Ses Bilgisi":["Ses olayını bulurken sözcüğün kökü ile ek almış biçimini karşılaştır.","Kaynaştırma harfi, ünlü daralması, yumuşama ve benzeşmenin koşullarını ayrı tut.","Yazımdaki her harf değişimini aynı ses olayı saymak."],
    "Yazım Kuralları":["Birleşik sözcükler, de/da, ki, mi ve büyük harf kullanımını cümledeki görevine göre denetle.","Bağlaç olan de/da ayrı; bulunma hâli eki bitişik yazılır ve ek büyük ünlü uyumuna uyar.","Özel ada gelen her eki kesmeyle ayırmak; yapım eklerini de kesmek."],
    "Noktalama":["İşaretin adını değil cümlede üstlendiği ayırma, açıklama veya vurgu görevini düşün.","Virgülün özne–yüklem arasına gelişigüzel konamayacağını ve iki noktanın açıklama beklentisi oluşturduğunu unutma.","Konuşma çizgisi, kısa çizgi ve uzun çizgiyi aynı görevde kullanmak."],
    "Sözcükte Yapı":["Kök, gövde, yapım eki ve çekim ekini sözcüğün anlam ve görev değişimine göre ayır.","Bir ekin biçiminden çok sözcükteki işlevine bak; aynı biçim farklı görev üstlenebilir.","Her sondaki eki yapım eki sanmak veya kökü yanlış yerde ayırmak."],
    "Sözcük Türleri":["Türü, sözcüğün cümledeki görevine göre belirle; aynı sözcük ad, sıfat veya zarf olabilir.","Sıfatın adı, zarfın ise fiil/sıfat/zarfı nitelediğini kontrol et.","Sözcüğü cümleden çıkarıp kalıcı bir tür etiketi vermek."],
    "Fiiller":["Kip, kişi, zaman/anlam kayması ve çatıyı yüklem üzerinden ayrı ayrı incele.","Birleşik zaman ile birleşik fiili karıştırma; biri çekim, diğeri yapı özelliğidir.","Kip ekini gördüğü anda cümlenin gerçek zamanını bağlamdan kontrol etmemek."],
    "Fiilimsi":["İsim-fiil, sıfat-fiil ve zarf-fiili ek kadar cümledeki görevinden tanı.","Kalıplaşmış isimleri ve çekimli fiilleri fiilimsi sanmamaya dikkat et.","Fiilimsi eki taşıyan her sözcüğü yüklemden bağımsız fiilimsi kabul etmek."],
    "Ek Fiil":["Ek fiil isim soylu sözcükleri yüklem yapar veya fiillerde birleşik zaman kurar.","Ek fiilin düşebildiği ve ayrı/bitişik yazılabildiği biçimleri bağlamda ara.","Her “-dir” biçimini yalnız bildirme eki sayıp zaman/kip işlevini kaçırmak."],
    "Cümlenin Ögeleri":["Önce yüklemi, sonra yükleme doğru soruları sorarak özne, nesne ve tümleçleri bul.","Söz öbeklerini bölme; edat grubu veya tamlama tek öge olabilir.","Devrik cümlede sözcük sırasını öge sırası sanmak."],
    "Cümle Türleri":["Cümleyi yüklemin türü/yeri, anlamı ve yapısı bakımından ayrı ölçütlerle sınıflandır.","Bağlaç bulunan her cümlenin mutlaka birleşik cümle olmayacağını unutma.","Bir sınıflandırmanın ölçütünü diğerine taşımak."],
    "Anlatım Bozukluğu":["Anlam bozukluklarıyla dil bilgisi bozukluklarını ayrı kontrol listeleriyle tara.","Gereksiz sözcük, yanlış anlam, özne–yüklem ve tamlama uyumsuzluğunu cümlenin tamamında denetle.","Kulağa yabancı gelen her cümleyi bozuk saymak; somut gerekçeyi bulamamak."],

    /* Matematik ve Geometri */
    "Temel Kavramlar":["Sayı kümeleri, işlem önceliği, tek–çift, pozitif–negatif ve ardışık sayı özelliklerini koşullarıyla kullan.","Sıfırın çift olduğunu; ancak pozitif ya da negatif olmadığını unutma.","Bölme veya sadeleştirme sırasında sıfır olabilecek ifadeyi yok etmek."],
    "Sayı Basamakları":["Basamak değeri ile sayı değerini ayır; sayıyı onluk tabanda cebirsel biçimde yaz.","Baş basamağın sıfır olamayacağını ve rakamların 0–9 aralığında olduğunu her çözümde uygula.","Rakam toplamı koşulunu sayı değeri koşuluyla karıştırmak."],
    "Sayılar":["Tam, rasyonel, irrasyonel ve gerçek sayı kümelerinin kapsama ilişkisini bil.","Negatif sayılarda sıralama ve çift/tek kuvvetlerin işaret etkisini ayrıca kontrol et.","Kök içeren her sayıyı irrasyonel kabul etmek."],
    "Bölme-Bölünebilme":["Bölme algoritmasını bölünen=bölen×bölüm+kalan biçiminde kur; 0≤kalan<bölen koşulunu koru.","Bölünebilme kurallarını sayının tamamına ve istenen bölenin asal çarpanlarına göre uygula.","Kalanları doğrudan çarpıp/toplayıp mod kontrolü yapmadan sonuçlandırmak."],
    "EBOB-EKOK":["EBOB ortak bölenlerin, EKOK ortak katların en uç değeridir; asal çarpan üslerini doğru seç.","İki pozitif tam sayı için EBOB×EKOK=sayıların çarpımı ilişkisini yalnız uygun koşulda kullan.","Parça sayısı sorusunda EBOB yerine EKOK seçmek veya artan parça/işlem sayısını karıştırmak."],
    "Rasyonel Sayılar":["Payda sıfır olamaz; karşılaştırmada işaret ve ortak payda kontrolü yap.","Negatif kesirlerde pay/payda işaretlerinin sadeleşmesini sayı doğrusuyla doğrula.","Kesirlerde toplama yaparken pay ve paydayı ayrı ayrı toplamak."],
    "Ondalıklı Sayılar":["Sonlu ve devirli ondalıkları kesre çevirirken basamak sayısını doğru kullan.","Virgül kaydırırken sayıyı 10'un uygun kuvvetiyle çarpıp böldüğünü takip et.","Devir çizgisinin kapsadığı basamakları eksik almak."],
    "Basit Eşitsizlik":["Negatif sayıyla çarpma veya bölmede eşitsizlik yönünün değiştiğini unutma.","Çözümü sayı doğrusu ve aralık gösterimiyle son kez kontrol et.","Paydada değişken varken işaret tablosu kurmadan içler–dışlar çarpımı yapmak."],
    "Mutlak Değer":["Mutlak değeri sayının sıfıra uzaklığı olarak düşün; parçalı tanımı işarete göre kur.","|x|≥a ve |x|≤a kalıplarında a'nın işaretini ve çözüm biçimini kontrol et.","Mutlak değerin içini koşulsuz pozitif kabul edip |x|=x yazmak."],
    "Üslü Sayılar":["Aynı tabanda çarpma/bölme ve kuvvetin kuvveti kurallarını taban koşullarıyla uygula.","Negatif tabanda parantez ile üs paritesinin sonucu değiştirdiğini kontrol et.","Toplama işleminde üsleri toplamak veya (a+b)^n'i terim terim üslemek."],
    "Köklü Sayılar":["Çift dereceli kökte kök içinin negatif olamayacağını; √(a²)=|a| olduğunu bil.","Kök dışına çıkarma ve payda rasyonelleştirmede işaret/çarpan kontrolü yap.","√(a+b)=√a+√b gibi geçersiz dağıtma yapmak."],
    "Çarpanlara Ayırma":["Ortak çarpan, iki kare farkı ve tam kare özdeşliklerini ifade yapısına göre seç.","Çarpanlara ayırdıktan sonra çarparak ilk ifadeyi verip vermediğini kontrol et.","Ortak çarpanı eksik almak veya orta terimin işaretini kaçırmak."],
    "Oran-Orantı":["Oranlanan niceliklerin aynı tür ve birimde olmasını sağla; doğru ve ters orantıyı yön değişiminden tanı.","Orantı sabitini kurmadan tablo üzerinden gelişigüzel içler–dışlar çarpımı yapma.","Ters orantıda iki büyüklüğü aynı yönde değiştirmek."],
    "Denklem Çözme":["Tanım koşullarını başta yaz, eşdeğer dönüşümlerle ilerle ve bulunan kökü asıl denklemde denetle.","Payda, kök ve mutlak değer içeren denklemlerde yabancı kök oluşabileceğini unutma.","Her iki tarafın karesini aldıktan sonra kök kontrolünü atlamak."],
    "Problemler":["Bilinmeyeni açık tanımla, verilenleri birimlerle tablo/denklem hâline getir ve isteneni son cümlede yeniden oku.","Yüzde, hız, işçi, karışım ve yaş sorularında başlangıç–değişim–sonuç düzenini koru.","Bulduğu ara değeri sorunun istediği sonuç sanmak veya birimleri eşitlememek."],
    "Kümeler":["Birleşim, kesişim, fark ve tümleyeni Venn şemasıyla ilişkilendir.","Eleman ile alt küme sembollerini; boş küme ile boş kümeyi eleman alan kümeyi ayır.","n(A∪B) hesabında kesişimi çıkarmayı unutmak."],
    "Mantık":["Önerme, doğruluk değeri, bağlaçlar, koşullu önerme ve niceleyicileri sembol–Türkçe arasında çevirebil.","p⇒q önermesinin yalnız p doğru, q yanlışken yanlış olduğunu bil.","Bir önermenin değili alınırken bağlacı veya niceleyiciyi değiştirmemek."],
    "Fonksiyonlar":["Tanım kümesindeki her elemanın görüntü kümesinde tam bir görüntüsü olmalı; birebir/örten ayrı özelliklerdir.","Bileşke ve ters fonksiyonda işlem sırasını ve tanım–değer kümelerini izle.","f(x) ifadesini f ile x'in çarpımı sanmak ya da ters fonksiyonu 1/f ile karıştırmak."],
    "Polinomlar":["Polinomda üsler negatif olmayan tam sayı olmalı; derece, katsayı ve sabit terimi doğru oku.","Kalan teoreminde P(a)'nın x−a ile bölümden kalanı verdiğini işaretle birlikte kullan.","x+a böleni için P(a) yazmak; doğru değer P(−a)'dır."],
    "İkinci Dereceden Denklemler":["Diskriminant kök sayısını; kökler toplamı ve çarpımı katsayı ilişkilerini verir.","Parametre sorularında istenen kök türüne göre Δ ve katsayı koşullarını birlikte kur.","Denklemi standart biçime getirmeden katsayıları okumak."],
    "Permütasyon-Kombinasyon":["Sıra önemliyse permütasyon, yalnız seçim önemliyse kombinasyon kullan; aşamaları çarpma/toplama ilkesiyle ayır.","Tekrarlı öğe, yan yana/ayrı olma ve dairesel diziliş koşullarını başta belirle.","Aynı düzeni birden fazla saymak veya tamamlayıcı durumu eksik bırakmak."],
    "Olasılık":["Eş olasılıklı durumda olasılığı uygun durum/tüm durum olarak kur; 0 ile 1 arasında kontrol et.","Bağımsız olay ile ayrık olayı karıştırma; koşullu olasılıkta örnek uzayı güncelle.","“En az bir” sorusunda tamamlayıcı olasılığı hesaba katmamak."],
    "Veri ve İstatistik":["Aritmetik ortalama, ortanca, tepe değer ve açıklığın farklı özellikleri ölçtüğünü bil.","Grafik ölçeği, kırık eksen, yüzde–frekans ve örneklem büyüklüğünü okumadan yorum yapma.","Ortalama değişimini toplam veri sayısını hesaba katmadan hesaplamak."],
    "Üçgenler":["Açı–kenar ilişkileri, üçgen eşitsizliği, benzerlik, alan ve özel üçgenleri aynı şekil üzerinde bağla.","Benzerlik oranında uzunluk, alan ve hacim oranlarının farklı kuvvetlerde olduğunu unutma.","Şekilde görünene göre ikizkenar/dik üçgen varsaymak."],
    "Çokgenler":["İç açı toplamı (n−2)·180°, dış açı toplamı 360°; düzgünlük koşulunu ayrıca ara.","Köşegen sayısı ve bir köşeden çizilen köşegen sayısını ayır.","Düzgün olmayan çokgende tüm açıları eşit kabul etmek."],
    "Dörtgenler":["Paralelkenar, dikdörtgen, eşkenar dörtgen, kare ve yamuk özelliklerinin kapsama ilişkisini bil.","Köşegen özelliklerinin her dörtgende aynı olmadığını şeklin özel türüne göre kontrol et.","Bir özelliğin tersinin her zaman doğru olduğunu varsaymak."],
    "Çember-Daire":["Çember çevreyi, daire iç bölgeyi anlatır; merkez açı, çevre açı, teğet ve kiriş ilişkilerini ayır.","Yay uzunluğu ile daire dilimi alanında açı/360 oranını doğru büyüklüğe uygula.","Teğetin yarıçapa değme noktasında dik olduğunu kullanmamak."],
    "Analitik Geometri":["Noktalar arası uzaklık, orta nokta ve doğru eğimini koordinat işaretleriyle hesapla.","Dikey doğrunun eğiminin tanımsız olduğunu ve paralel/dik doğruların eğim ilişkilerini ayır.","Eğim formülünde x ve y farklarının sırasını farklı almak."],
    "Katı Cisimler":["Yüzey alanı ile hacmi ayır; uzunluk ölçeği değişince alanın karesi, hacmin küpüyle değiştiğini bil.","Açınım, taban alanı ve dik yüksekliği şekil üzerinde göster.","Eğik ayrıtı dik yükseklik yerine kullanmak."],
    "Karmaşık Sayılar":["i²=−1 döngüsünü ve z=a+bi gösterimini kullan; eşitlikte gerçek/sanal kısımları ayrı eşitle.","Eşlenik çarpımın a²+b² verdiğini ve karmaşık düzlemde modülü yorumla.","√(−a) işlemlerinde i'yi unutmak veya i üs döngüsünü yanlış başlatmak."],
    "Logaritma":["Taban pozitif ve 1'den farklı; logaritmanın içi pozitif olmalıdır.","Çarpımı toplam, bölümü fark, üssü katsayı yapan kuralları yalnız tanım koşullarıyla uygula.","log(a+b)'yi loga+logb biçiminde ayırmak."],
    "Diziler":["Terim numarası ile terim değerini ayır; aritmetik/geometrik dizide ortak fark/oranı doğrula.","Toplam formüllerinde ilk terim, son terim ve terim sayısını eşleştir.","Genel terimi bulurken indeksin 0 mı 1 mi başladığını gözden kaçırmak."],
    "Limit":["Noktadaki değer ile o noktaya yaklaşırken oluşan limiti ayır; sağ ve sol limit eşit olmalı.","Belirsizlikte doğrudan sonuç vermek yerine cebirsel düzenleme veya eşlenik kullan.","0/0 ifadesini limitin sıfır olduğu şeklinde yorumlamak."],
    "Türev":["Türevi anlık değişim/eğim olarak yorumla; tanım kümesi ve türevlenebilirlik koşullarını incele.","Artan–azalan, ekstremum ve teğet sorularında türev işaret tablosunu kur.","f'(x)=0 olan her noktayı koşulsuz ekstremum kabul etmek."],
    "İntegral":["Belirsiz integralde sabit C'yi; belirli integralde yönlü alan ile geometrik alan farkını koru.","Sınırlar ters çevrilince işaretin değiştiğini ve eksen altındaki alanın negatif katkı verdiğini bil.","Alan sorusunda integrali mutlak alan kontrolü yapmadan bırakmak."],
    "Trigonometri":["Birim çemberde açı, yön, bölge ve işareti belirle; özdeşlikleri buradan doğrula.","Derece–radyan dönüşümü ile periyot ve esas ölçüyü karıştırma.","sin(a+b)'yi sina+sinb gibi dağıtmak."],
    "Analitik-Doğru":["Doğrunun eğim, açı, nokta ve denklem gösterimlerini birbirine dönüştür.","Dikey/yatay doğrular ile paralellik ve diklik özel durumlarını ayrı kontrol et.","Dik doğrularda eğim çarpımı kuralını eğimi tanımsız doğruya uygulamak."],
    "Analitik-Çember":["Çember denklemini merkez ve yarıçapla ilişkilendir; genel denklemde kare tamamlama yap.","Doğru–çember konumunda merkezden doğruya uzaklıkla yarıçapı karşılaştır.","Yarıçap karesi ile yarıçapı karıştırmak."],
    "Dönüşümler":["Öteleme, yansıma ve dönmede noktanın koordinat değişimini referans eksen/merkeze göre izle.","Dönme yönü ve açı işaretini; yansımada hangi koordinatın değiştiğini kontrol et.","Dönüşüm sırasının sonucu değiştirebileceğini unutmak."],

    /* Fizik */
    "Fizik Bilimine Giriş":["Temel/türetilmiş, skaler/vektörel büyüklükleri ve SI birimlerini ayır.","Ölçüm sonucu ile birimini birlikte yaz; bilimsel gösterimde mertebeyi koru.","Birim dönüşümünde alan ve hacim için dönüşüm katsayısının kuvvetini almamak."],
    "Madde ve Özellikleri":["Özkütleyi m/V olarak yorumla; kütle madde miktarı, hacim kaplanan uzaydır.","Sıcaklık ve hâl değişimi gibi koşulların hacim/özkütleye etkisini göz önünde bulundur.","Aynı maddeden büyük parçanın özkütlesinin daha büyük olduğunu sanmak."],
    "Hareket ve Kuvvet":["Konum, alınan yol, yer değiştirme, sürat ve hızı yönleriyle ayır.","Net kuvvet sıfırken cismin durmak zorunda olmadığını; sabit hızla gidebileceğini bil.","Hız–zaman grafiğinin eğimini hız sanmak; eğim ivmedir."],
    "İş-Güç-Enerji":["İş için kuvvetin yer değiştirme doğrultusundaki bileşenini kullan; güç iş/zamandır.","Enerji korunumu ile mekanik enerji korunumu koşullarını aynı sayma.","Cisim hareket ettiği için her kuvvetin iş yaptığını kabul etmek."],
    "Isı-Sıcaklık-Genleşme":["Isı enerji aktarımıdır, sıcaklık taneciklerin ortalama kinetik enerjisiyle ilişkilidir.","Hâl değişiminde sıcaklığın sabit kalabildiğini; ısı alışverişinin sürdüğünü unutma.","Eşit sıcaklıktaki cisimlerin ısılarının eşit olduğunu söylemek."],
    "Basınç":["Katı, sıvı ve gaz basıncında etkili değişkenleri ayrı modellerle değerlendir.","Sıvı basıncı kap şekline değil derinlik, yoğunluk ve yerçekimine bağlıdır.","Basınç kuvveti ile basıncı aynı büyüklük sanmak."],
    "Kaldırma Kuvveti":["Kaldırma kuvveti yer değiştiren akışkanın ağırlığına eşittir.","Yüzen, askıda ve batan cisimlerde kuvvet/özkütle ilişkilerini ayrı kur.","Sıvıya daha derin batınca tamamen batmış cismin kaldırma kuvvetinin mutlaka artacağını sanmak."],
    "Elektrostatik":["Yük korunur; iletkenlerde yük dağılımı ve etki ile elektriklenmeyi ayır.","Coulomb kuvvetinde uzaklığın karesi ve yüklerin işareti/yönü önemlidir.","Nötr cisimde hiç yük olmadığını sanmak."],
    "Elektrik ve Manyetizma":["Akım, gerilim ve direnç ilişkisini devre bağlantısına göre kur; seri/paralel eşdeğeri ayır.","Ampermetreyi seri, voltmetreyi paralel bağla; ideal ölçü aletlerinin dirençlerini hatırla.","Paralel kollarda akımın da gerilim gibi eşit olduğunu varsaymak."],
    "Optik":["Işın çiziminde normal, gelme/yansıma açıları ve ortam değişimindeki kırılma yönünü göster.","Gerçek–sanal görüntü ile düz–ters ve büyük–küçük özelliklerini araç türüne göre ayır.","Açıları yüzeye göre ölçmek; optikte açılar normale göredir."],
    "Dalgalar":["v=fλ ilişkisini kullan; kaynak frekansı ile ortamın dalga hızına etkisini ayır.","Yansıma, kırılma, girişim ve atmalarda yön/faz bilgisini çizerek izle.","Ortam değişince frekansın da değiştiğini sanmak."],
    "Vektörler":["Vektörleri bileşenlerine ayır; büyüklük ve yönü birlikte koru.","Toplamada uç uca ekleme/paralelkenar yöntemini ve eksen işaretlerini denetle.","Vektör büyüklüklerini yön bilgisi olmadan doğrudan toplamak."],
    "Kuvvet-Denge":["Denge için net kuvvetin ve net torkun sıfır olması gerekir.","Serbest cisim diyagramına yalnız cisme etki eden kuvvetleri ekle.","Etki–tepki kuvvetlerini aynı cisim üzerinde gösterip birbirini yok etmek."],
    "Tork":["Torku kuvvet×dik uzaklık olarak hesapla; dönme yönüne göre işaret ver.","Kuvvetin uygulama noktasından çok dönme eksenine dik uzaklığı belirleyicidir.","Kuvvet kolu yerine eğik uzunluğun tamamını kullanmak."],
    "Basit Makineler":["İdeal makinede işten kazanç yoktur; kuvvet kazancı yol kaybıyla dengelenir.","Makine verimi ve mekanik avantajı aynı kavram sanma.","Sabit makarada kuvvet kazancı olduğunu varsaymak."],
    "Newton Yasaları":["Net kuvveti ma ile ilişkilendir; eylemsizlik sistemini ve ivme yönünü belirle.","Sürtünmenin her zaman harekete değil göreli kayma eğilimine zıt olduğunu düşün.","Ağırlık ile normal kuvveti her durumda eşit almak."],
    "İtme-Momentum":["İtme momentum değişimine eşittir; momentum vektöreldir ve sistem için korunur.","Çarpışma türünde momentum korunumu ile kinetik enerji korunumunu ayrı denetle.","Cisimlerin momentum büyüklüklerini yönsüz toplamak."],
    "Elektrik-Manyetizma":["Elektrik alan/potansiyel ile manyetik alan/kuvvet kavramlarını yön ve birimleriyle ayır.","Manyetik kuvvetin hareketli yüke dik olduğunu ve iş yapmadığını uygun durumda kullan.","Potansiyel sıfır olan noktada elektrik alanın da mutlaka sıfır olduğunu sanmak."],
    "Çembersel Hareket":["Merkezcil kuvvet ayrı bir kuvvet değil, merkeze doğru net kuvvetin adıdır.","Çizgisel ve açısal büyüklükleri v=ωr ile bağla; periyot–frekansı ayır.","Sabit süratli çembersel harekette ivme yok demek."],
    "Basit Harmonik Hareket":["Geri çağırıcı kuvvet denge konumuna yönelir; hız ve ivme konuma göre değişir.","Uç ve denge konumlarında hız, ivme ve enerjinin hangi uç değerde olduğunu karşılaştır.","Periyodu genlik arttıkça her sistemde artar sanmak."],
    "Dalga Mekaniği":["Girişim, kırınım ve duran dalgada yol farkı/faz koşullarını çizerek kur.","Düğüm–karın noktaları ile temel frekans/harmonik ilişkisini sınır koşuluna göre belirle.","Her frekansın verilen ortamda duran dalga oluşturacağını kabul etmek."],
    "Modern Fizik":["Fotoelektrik, özel görelilik, atom modelleri ve kuantum kavramlarını klasik fizikten ayrıldığı noktayla öğren.","Foton enerjisi ile ışık şiddetinin etkilerini karıştırma.","Fotoelektrikte şiddeti artırınca kopan elektronların maksimum kinetik enerjisinin arttığını sanmak."],

    /* Kimya */
    "Kimya Bilimi":["Kimyanın alt disiplinlerini, laboratuvar güvenlik işaretlerini ve temel araçların kullanımını bil.","Kimyasal maddeyi etiketi ve güvenlik bilgisi olmadan özellik tahminiyle kullanma.","Laboratuvar kabını kullanım amacı yerine şekline bakarak seçmek."],
    "Atom ve Yapısı":["Proton atom numarasını, proton+nötron kütle numarasını verir; iyonlarda elektron sayısı yükle değişir.","İzotop, izobar, izoton ve izoelektronik tanımlarında hangi niceliğin eşit olduğunu ayır.","İyon oluşurken proton sayısının değiştiğini sanmak."],
    "Periyodik Sistem":["Periyodik özellikleri etkin çekirdek yükü, katman sayısı ve elektron dizilimiyle açıkla.","Atom yarıçapı ile iyonlaşma enerjisi/elektronegatiflik eğilimlerinin genellikle ters yönlü olduğunu izle.","İyon yarıçapını nötr atomla yalnız periyot eğilimine göre karşılaştırmak."],
    "Kimyasal Türler Arası Etkileşim":["Güçlü bağları tanecik içi, zayıf etkileşimleri tanecikler arası düzeyde ayır.","Hidrojen bağı için H'nin F, O veya N'a bağlı olma koşulunu kontrol et.","Molekül içi kovalent bağı moleküller arası çekimle karıştırmak."],
    "Maddenin Halleri":["Taneciklerin hareketi, aralıkları ve çekim kuvvetlerini katı–sıvı–gaz hâlleriyle ilişkilendir.","Hâl değişiminde potansiyel enerji ve sıcaklık değişimini ayrı izle.","Kaynama ile buharlaşmayı aynı koşullara bağlı olay sanmak."],
    "Kimyanın Temel Kanunları":["Kütlenin korunumu, sabit oranlar ve katlı oranlar kanunlarını verilen niceliklerden tanı.","Katlı oranlarda aynı iki elementin farklı bileşiklerini ve sabit element miktarını karşılaştır.","Bileşik yerine karışım verisinde sabit oran aramak."],
    "Mol Kavramı":["Molü tanecik sayısı, kütle ve uygun koşulda gaz hacmi arasında köprü olarak kullan.","Tanecik türünü—atom, molekül, iyon veya formül birimi—soruda açıkça belirle.","Bir mol her maddenin aynı kütlesidir sanmak."],
    "Kimyasal Hesaplamalar":["Önce tepkimeyi denkleştir, sonra mol oranını kullan; sınırlayıcı bileşeni kontrol et.","Verim, saflık ve artan madde sorularında başlangıç–harcanan–kalan tablosu kur.","Katsayı oranlarını doğrudan gram oranı olarak kullanmak."],
    "Karışımlar":["Homojen/heterojen sınıflandırmasını tanecik dağılımına; ayırma yöntemini fiziksel özellik farkına bağla.","Yüzde derişimde çözünen, çözücü ve çözelti kütlelerini doğru yere yaz.","Çözeltiye su eklenince çözünen miktarının değiştiğini sanmak."],
    "Asit-Baz-Tuz":["Asit–baz tanımlarını, pH–pOH ilişkisini ve nötralleşmeyi koşullarıyla kullan.","Güçlü/zayıf ile derişik/seyreltik kavramlarını ayrı eksenlerde değerlendir.","pH değerlerini doğrusal ölçek gibi yorumlamak."],
    "Kimya Her Yerde":["Temizlik, gıda, ilaç ve malzeme kimyasını etken madde–işlev–güvenlik ilişkisiyle öğren.","Ürünleri karıştırmanın tehlikeli tepkimeler oluşturabileceğini güvenlik bağlamında değerlendir.","“Doğal” olan her maddenin zararsız olduğunu varsaymak."],
    "Modern Atom Teorisi":["Kuantum sayıları, orbital türleri ve elektron dizilimini Aufbau, Pauli ve Hund ilkeleriyle kur.","İyonlaşmada elektronların en büyük ana kuantum sayılı düzeyden ayrıldığını kontrol et.","Geçiş metali iyonunda elektronları 3d'den önce değil 4s'den çıkarmayı unutmak."],
    "Gazlar":["P, V, n ve T ilişkilerinde sıcaklığı Kelvin kullan; ideal gaz varsayımlarını bil.","Kısmi basınçta yalnız gaz fazındaki mol kesrini kullan.","Santigrat sıcaklığı doğrudan gaz denklemlerine koymak."],
    "Sıvı Çözeltiler":["Molarite, molalite ve yüzde derişimin payda türlerini ayır; koligatif özelliği tanecik sayısıyla ilişkilendir.","İyonik çözünenlerde van't Hoff/tanecik etkisini ideal yaklaşımda hesaba kat.","Molariteyi çözücü hacmine göre hesaplamak; payda çözelti hacmidir."],
    "Kimyasal Tepkimelerde Enerji":["Entalpi değişiminin işaretini sisteme göre; bağ enerjisini kırılan–oluşan bağlarla hesapla.","Katalizörün aktivasyon enerjisini düşürüp tepkime entalpisini değiştirmediğini bil.","Ekzotermik tepkimede sistemin enerjisinin arttığını sanmak."],
    "Kimyasal Tepkimelerde Hız":["Hızın derişim, sıcaklık, yüzey alanı ve katalizörle çarpışma sayısı/enerjisi üzerinden değiştiğini açıkla.","Hız bağıntısındaki derecelerin her zaman denklem katsayılarından gelmediğini unutma.","Katalizörün denge sabitini veya ürün miktarını değiştirdiğini sanmak."],
    "Kimyasal Denge":["Denge dinamiktir; ileri ve geri hızlar eşittir, derişimler zorunlu olarak eşit değildir.","Q ile K karşılaştırmasında tepkimenin ilerleme yönünü; Le Châtelier'de sistemi etkileyen değişimi belirle.","Saf katı ve sıvıları denge bağıntısına yazmak."],
    "Asit-Baz Dengesi":["Ka, Kb, suyun iyonlaşması, tampon ve hidroliz hesaplarında türleri ve yaklaşımı seç.","Kuvvetli/zayıf asit-baz ayrımıyla derişimi birbirine karıştırma.","Zayıf asidin tamamen iyonlaştığını kabul etmek."],
    "Çözünürlük Dengesi":["Kçç bağıntısını dengelenmiş çözünme denkleminden yaz; iyon katsayılarını üs yap.","Ortak iyonun çözünürlüğü azaltmasını ve çökelme için iyon çarpımı–Kçç karşılaştırmasını kullan.","Kçç ile molar çözünürlüğü aynı saymak."],
    "Elektrokimya":["Anotta yükseltgenme, katotta indirgenme olur; elektron akışını anottan katoda izle.","Galvanik ve elektrolitik hücrede elektrot işaretlerinin farklı olabileceğini unutma.","Tuz köprüsünden elektron geçtiğini sanmak."],
    "Organik Kimya":["Fonksiyonel grubu, adlandırmayı, izomerliği ve temel tepkime türlerini karbon iskeleti üzerinden öğren.","En uzun zincir, numaralandırma önceliği ve doymuş/doymamışlık kontrolünü sırayla yap.","Aynı molekül formülüne sahip her yapıyı aynı bileşik kabul etmek."],

    /* Biyoloji */
    "Canlıların Ortak Özellikleri":["Hücresel yapı, metabolizma, homeostazi, büyüme, üreme ve adaptasyonu canlılık bağlamında ayır.","Bireysel uyum ile nesiller boyunca seçilen kalıtsal adaptasyonu karıştırma.","Üremeyi bireyin yaşamı için zorunlu ortak özellik sanmak."],
    "Canlıların Temel Bileşenleri":["İnorganik ve organik bileşenleri yapı, görev ve enerji verme durumlarıyla karşılaştır.","Enzimlerin aktivasyon enerjisini düşürdüğünü, harcanmadığını ve özgüllüğünü bil.","Vitamin, mineral veya suyun enerji verdiğini düşünmek."],
    "Hücre":["Prokaryot–ökaryot ve bitki–hayvan hücresini organel, zar ve genetik materyal açısından karşılaştır.","Organel görevlerini tek başına değil hücre içi madde/enerji akışıyla ilişkilendir.","Bütün hücrelerde çekirdek veya zarlı organel bulunduğunu sanmak."],
    "Madde Geçişleri":["Difüzyon, osmoz, aktif taşıma, endositoz ve ekzositozu enerji, yön ve zar geçişiyle ayır.","Hipotonik/hipertonik ortamı hücreye göre tanımla; suyun hareket yönünü çözünen derişiminden çıkar.","Aktif taşımayı yalnız çok maddeden az maddeye geçiş sanmak."],
    "Canlıların Sınıflandırılması":["Sınıflandırmada akrabalık, homolog yapı ve moleküler benzerliği; takson basamaklarını birlikte kullan.","Türden âleme gidildikçe ortak özellik azalırken birey sayısının arttığını izle.","Analog organ benzerliğini yakın akrabalığın kesin kanıtı saymak."],
    "Hücre Bölünmeleri":["Mitoz ve mayozu amaç, bölünme sayısı, kromozom sayısı ve genetik çeşitlilik açısından karşılaştır.","DNA eşlenmesinin interfazda bir kez olduğunu; kardeş kromatit/homolog kromozom ayrımını bil.","Kromozom sayısını kromatit veya DNA miktarıyla aynı saymak."],
    "Üreme":["Eşeyli ve eşeysiz üremeyi gamet, döllenme ve genetik çeşitlilik bakımından karşılaştır.","Üreme hücresi oluşumu ile döllenme sonrası gelişim basamaklarını ayrı izle.","Eşeysiz üremenin her zaman mutasyonsuz ve tamamen özdeş bireyler oluşturduğunu kesin kabul etmek."],
    "Kalıtım":["Gen, alel, genotip, fenotip, baskınlık ve çaprazlamayı olasılık diliyle bağla.","Bağımsız dağılım, bağlı gen, eş baskınlık ve çok alelliliğin klasik Mendel oranlarını değiştirebileceğini bil.","Baskın alelin toplumda mutlaka daha yaygın olduğunu sanmak."],
    "Ekosistem Ekolojisi":["Enerji akışı tek yönlü, madde döngüleri devridir; trofik düzeyler arasında enerji azalır.","Besin ağı değişimlerinde doğrudan ve dolaylı etkileri ayrı izle.","Üst basamağa çıkıldıkça biriken enerji veya biyokütlenin arttığını sanmak."],
    "Çevre Sorunları":["Kirlilik, iklim değişikliği, biyoçeşitlilik kaybı ve sürdürülebilirliği neden–etki–çözüm zinciriyle değerlendir.","Yerel bir çevre olayının küresel sonuçlarını ve geri bildirimlerini ayır.","Her yenilenebilir kaynağın çevresel etkisiz olduğunu varsaymak."],
    "Sinir Sistemi":["Nöronda impuls oluşumu/iletimi ile sinapsta aktarımı; merkezî ve çevresel sistemi ayır.","İmpuls şiddetinin frekansla kodlandığını; tek impuls büyüklüğünün değişmediğini bil.","Dendritten aksona tüm bağlantılarda aynı kimyasal iletim olduğunu sanmak."],
    "Endokrin Sistem":["Hormon–bez–hedef organ–etki eşleştirmesini geri bildirim mekanizmasıyla kur.","Hormonun kanla taşınmasıyla yalnız hedef reseptörü taşıyan hücrede etki göstermesini ayır.","Her hormonun yalnız bir organda tek etki oluşturduğunu sanmak."],
    "Duyu Organları":["Reseptör, uyarı türü, iletim yolu ve beyindeki değerlendirme merkezini birlikte öğren.","Göz ve kulakta yapıların sırasını şema üzerinde izle.","Uyarının duyu organında bilinçli algıya dönüştüğünü sanmak."],
    "Destek-Hareket":["Kemik, eklem ve kas türlerini yapı–görev; kasılmayı aktin–miyozin ve enerji ilişkisiyle öğren.","Zıt çalışan kaslarda bir kasılırken diğerinin gevşediğini hareket yönüne göre belirle.","Kasılmada aktin ve miyozin ipliklerinin boylarının kısaldığını sanmak."],
    "Sindirim":["Mekanik ve kimyasal sindirimi; enzim, substrat, organ ve emilim yeriyle eşleştir.","Safranın enzim olmadığını ve yağları fiziksel olarak küçük damlalara ayırdığını bil.","Her besinin sindiriminin midede başladığını düşünmek."],
    "Dolaşım-Bağışıklık":["Kalbin bölmeleri, damarlar, küçük/büyük dolaşım ve kan bileşenlerini akış yönüyle öğren.","Doğuştan ve kazanılmış; aktif ve pasif bağışıklığı kaynak ve hafıza açısından ayır.","Atardamarın her zaman oksijence zengin kan taşıdığını sanmak."],
    "Solunum":["Gaz alışverişi ile hücresel solunumu; ventilasyon ile difüzyonu ayrı süreçler olarak gör.","Oksijen ve karbondioksit taşınma biçimlerini kanda bulunduğu yapıyla eşleştir.","Soluk vermenin her durumda tamamen pasif olduğunu genellemek."],
    "Boşaltım":["Nefronda süzülme, geri emilim ve salgılamanın yerini ve madde yönünü izle.","ADH ve aldosteronun su–tuz dengesi üzerindeki farklı etkilerini ayır.","İdrarda bulunan her maddenin yalnız süzülmeyle geçtiğini sanmak."],
    "Genetik":["DNA replikasyonu, protein sentezi, mutasyon ve biyoteknolojiyi bilgi akışı üzerinden bağla.","Transkripsiyon ile translasyonun yeri, girdisi ve ürününü ayrı tut.","Her mutasyonun fenotipe yansıdığını veya kalıtsal olduğunu sanmak."],
    "Ekosistem":["Üretici–tüketici–ayrıştırıcı ilişkisini enerji piramidi, besin ağı ve madde döngüleriyle kur.","Popülasyon, komünite, ekosistem ve biyosfer düzeylerini karıştırma.","Enerjinin ekosistemde madde gibi döngü yaptığını söylemek."],
    "Komünite":["Rekabet, av–avcı, mutualizm, parazitizm ve süksesyonu türler arası etki işaretleriyle karşılaştır.","Temel niş ile gerçekleşen nişi ve birincil–ikincil süksesyonu ayır.","Aynı ortamı paylaşan her iki tür arasında mutlaka rekabet olduğunu varsaymak."],
    "Popülasyon":["Popülasyon büyüklüğünü doğum, ölüm, içe/dışa göç; büyümeyi taşıma kapasitesiyle yorumla.","Yoğunluğa bağlı ve bağımsız faktörleri ayır; yaş dağılımı grafiğini geleceğe dönük oku.","Büyüme hızını popülasyon büyüklüğüyle aynı şey sanmak."],
    "Bitki Biyolojisi":["Bitki dokuları, taşıma, hormonlar, tropizmalar ve üremeyi yapı–işlev ilişkisiyle öğren.","Ksilem/floemde taşınan madde, yön ve mekanizmayı ayrı karşılaştır.","Bitkilerde tüm taşımanın yalnız kökten yaprağa olduğunu sanmak."],

    /* Tarih */
    "Tarih ve Zaman":["Kaynak türleri, tarih yazıcılığı, takvim ve çağ kavramlarını kanıt–yorum ayrımıyla öğren.","Birinci el kaynağın otomatik olarak tarafsız olmadığına dikkat et.","Olayın tarihini bilmenin neden ve sonuçlarını açıklamaya yettiğini sanmak."],
    "İlk ve Orta Çağlarda Türk Dünyası":["Bozkır kültürü, kut, töre, ikili teşkilat ve boylar federasyonunu devlet yapısıyla ilişkilendir.","Farklı Türk devletlerinin unvan, coğrafya ve dinî özelliklerini karıştırma.","Göçebe yaşamı yerleşiklikten tamamen yoksun ve değişmez saymak."],
    "İlk Uygarlıklar":["Uygarlıkları coğrafya, yönetim, hukuk, yazı ve bilim katkılarıyla karşılaştır.","Aynı buluşun ilk kullanım yeri ile yaygınlaştırıldığı uygarlığı ayır.","Coğrafi benzerlikten bütün uygarlıkların aynı siyasi yapıya sahip olduğu sonucunu çıkarmak."],
    "İslam Medeniyetinin Doğuşu":["İslam öncesi Arabistan, Hz. Muhammed dönemi ve Dört Halife gelişmelerini kronolojik bağla.","Hicretin nedenleri, sonuçları ve takvim başlangıcı olmasını ayrı ayrı bil.","Dinî gelişmeyle siyasi/askerî gelişmenin tarih sırasını karıştırmak."],
    "Türk-İslam Devletleri":["Karahanlı, Gazneli, Büyük Selçuklu ve Anadolu Türk devletlerini kurum, coğrafya ve kültürle karşılaştır.","İkta, atabeylik, gulam ve medrese kurumlarının amaçlarını ayır.","Bir devlette görülen kurumu bütün Türk-İslam devletlerine aynı biçimde aktarmak."],
    "Osmanlı Kuruluş":["Beylikten devlete geçişi iskân, istimâlet, fetih yönü ve Bizans/Balkan koşullarıyla açıkla.","Kuruluş dönemi savaşlarını sonuçları ve Osmanlı'nın büyüme yönüyle eşleştir.","Kuruluşu tek bir nedene bağlamak."],
    "Osmanlı Yükselme":["Merkezîleşme, fetihler, deniz siyaseti ve kurumlaşmayı padişah–olay–sonuç zincirinde kur.","İstanbul'un fethinin Türk ve dünya tarihi sonuçlarını ayrı sınıflandır.","Her zaferin kalıcı toprak kazanımı anlamına geldiğini varsaymak."],
    "Osmanlı Değişim Çağı":["XVI sonu–XVIII yüzyıl değişimlerini askerî, mali, idari ve toplumsal nedenlerle birlikte değerlendir.","Islahatların amacı, kapsamı ve örnek alınan modeli dönemlere göre ayır.","“Duraklama” etiketini her alanda kesintisiz gerileme sanmak."],
    "Avrupa ve Osmanlı":["Coğrafi keşifler, Rönesans, Reform, bilimsel devrim ve sanayileşmenin Osmanlı'ya etkilerini bağla.","Avrupa'daki gelişmelerin tarih ve sonuçlarını birbirine karıştırma.","Bir Avrupa gelişmesinin Osmanlı'yı aynı anda ve tek biçimde etkilediğini varsaymak."],
    "XX. Yüzyıl Başlarında Osmanlı":["Trablusgarp, Balkan ve I. Dünya savaşlarını cephe, antlaşma ve toprak sonuçlarıyla sırala.","Osmanlı'nın savaştığı cepheleri açılma amacı ve savunma/taarruz niteliğiyle ayır.","Savaşın bitiş antlaşmasıyla sonraki barış antlaşmasını karıştırmak."],
    "Milli Mücadele":["Genelgeler, kongreler, TBMM, cepheler ve antlaşmaları millî egemenlik süreci içinde sırala.","Hazırlık dönemi kararlarının ilk kez/tek kez/tüm yurdu kapsama özelliklerini ayır.","Yerel direniş kararıyla ulusal egemenlik kararını aynı saymak."],
    "Atatürkçülük ve Türk İnkılabı":["İnkılapları amaç, alan ve ilgili Atatürk ilkesiyle ilişkilendir.","Laiklik, halkçılık ve devletçilik gibi ilkelerin birbirini tamamlayabildiğini unutma.","Bir inkılabı yalnız tek ilkeyle ve tek sonuçla sınırlandırmak."],
    "Osmanlı Duraklama":["XVII. yüzyıl siyasi gelişmelerini iç isyanlar, merkezî yapı ve Avrupa güç dengesiyle birlikte incele.","Dönemin antlaşmalarını yön değiştiren maddeleriyle ayır.","Her başarısızlığın doğrudan toprak kaybıyla sonuçlandığını sanmak."],
    "Osmanlı Gerileme":["XVIII. yüzyıl savaş/antlaşmalarını diplomasi, ıslahat ve Avrupa'yı örnek alma süreciyle bağla.","Pasarofça, Belgrad ve Küçük Kaynarca'nın sonuçlarını birbirine karıştırma.","Islahatların yalnız askerî alanda kaldığını genellemek."],
    "Osmanlı Dağılma":["Milliyetçilik, büyük devlet politikaları, reformlar ve savaşları toprak kayıplarıyla kronolojik kur.","Tanzimat, Islahat ve meşrutiyetlerin hukuki/siyasi kapsamını ayır.","Fermanların doğrudan halk egemenliği getirdiğini varsaymak."],
    "İnkılap Tarihi":["Milli Mücadele'den Cumhuriyet kurumlaşmasına geçişi siyasi, hukuk, eğitim ve toplum alanlarında izle.","Saltanat, halifelik ve cumhuriyetle ilgili kararların tarih ve gerekçelerini ayır.","Aynı yıl gerçekleşen inkılapların neden–sonuç sırasını ters kurmak."],
    "Kurtuluş Savaşı":["Doğu, Güney ve Batı cephelerini taraf, komutan, savaş ve antlaşmalarıyla karşılaştır.","Askerî zaferlerin diplomatik sonuçlarını doğru antlaşmayla eşleştir.","Kuvayımilliye ile düzenli ordunun rol ve dönemini karıştırmak."],
    "Atatürk İlkeleri":["Altı ilkeyi amaç, anahtar kavram ve uygulama örnekleri üzerinden ayır.","Bir uygulamanın birden fazla ilkeyle ilişkilendirilebileceğini soru bağlamına göre değerlendir.","Anahtar bir sözcük gördüğü anda parçanın bütününü okumadan ilke seçmek."],
    "Çağdaş Türk-Dünya Tarihi":["I. Dünya Savaşı sonrası düzen, II. Dünya Savaşı, Soğuk Savaş ve küreselleşmeyi bloklar üzerinden kronolojik izle.","Türkiye'nin iç politikasıyla uluslararası ittifaklardaki yerini aynı zaman çizgisinde kontrol et.","Benzer ad taşıyan uluslararası örgütlerin amaç ve üyelerini karıştırmak."],
    "İlk Çağ Uygarlıkları":["Mezopotamya, Mısır, Anadolu, İran, Hint, Çin ve Akdeniz uygarlıklarını katkı ve yönetimleriyle kıyasla.","Yazı, hukuk, takvim ve alfabe gelişmelerinde ilk örnek ile yayılmayı ayır.","Bir kültürel katkıyı coğrafi yakınlığa bakarak yanlış uygarlığa vermek."],
    "Türklerin İlk Dönemleri":["İlk Türk devletlerinde siyasi yapı, toplum, ordu, hukuk ve inancı yazıtlarla ilişkilendir.","Asya Hun, Göktürk ve Uygur özelliklerini yerleşiklik ve kültür bakımından ayır.","Uygurlardaki değişimi bütün Türk devletlerinin ortak özelliği saymak."],
    "İslam Tarihi":["Hz. Muhammed, Dört Halife, Emevi ve Abbasi dönemlerini yönetim ve yayılma bakımından sırala.","Halifeliğin seçimle/hanedanla yürütüldüğü dönemleri ayır.","Aynı siyasi olayın mezhepsel ve idari sonuçlarını tek başlıkta eritmek."],
    "Osmanlı Siyasi Tarihi":["Kuruluştan dağılmaya savaş, antlaşma ve güç dengelerini dönem kırılmalarıyla öğren.","Antlaşmalarda taraf, madde ve önem bilgisini aynı kartta eşleştir.","Benzer coğrafyada yapılan savaşları yalnız yer adına göre karıştırmak."],
    "Osmanlı Kültür ve Medeniyeti":["Merkez, taşra, ordu, toprak, hukuk, eğitim ve ekonomi kurumlarını görevleriyle bağla.","Seyfiye, ilmiye ve kalemiye sınıflarını görev ve temsilcileriyle ayır.","Tımar sistemini yalnız toprak mülkiyeti sanmak."],
    "XX. Yüzyıl Türk ve Dünya Tarihi":["Dünya savaşları, ideolojiler, Soğuk Savaş ve Türkiye gelişmelerini eş zamanlı kronolojide izle.","Bir olayın oluş tarihiyle Türkiye'ye etkisinin görüldüğü tarihi ayır.","Blok üyeliği ile dönemsel iş birliğini aynı saymak."],
    "Atatürkçülük":["Atatürkçü düşüncenin temel niteliklerini ilkeler ve bütünleyici esaslarla ilişkilendir.","Millî egemenlik, bağımsızlık ve çağdaşlaşma kavramlarını örnek üzerinden ayır.","Atatürkçülüğü yalnız inkılap adlarının ezberine indirgemek."],
    "Soğuk Savaş Sonrası":["1991 sonrası yeni devletler, bölgesel çatışmalar, küreselleşme ve uluslararası örgütleri neden–sonuçla izle.","Soğuk Savaş'ın bitişiyle bütün ittifak ve sorunların sona ermediğini bil.","Yakın tarih olaylarının kronolojisini güncel çağrışımlarla tahmin etmek."],

    /* Coğrafya */
    "Doğa ve İnsan":["Doğal ve beşerî sistemlerin karşılıklı etkisini örnekler üzerinden değerlendir.","Determinizm yerine insanın teknoloji ve tercihleriyle çevre etkisini değiştirebildiğini düşün.","Her beşerî dağılışı yalnız iklimle açıklamak."],
    "Harita Bilgisi":["Ölçek, uzaklık, alan, izohips, profil ve koordinatı harita üzerindeki işaretlerden çöz.","Paydası büyük ölçeğin küçük olduğunu; ayrıntı ve gösterilen alan ilişkisini unutma.","Eğim hesabında yatay uzaklık yerine eğik yüzey uzunluğunu kullanmak."],
    "Dünyanın Şekli ve Hareketleri":["Geoit şeklin ve günlük/yıllık hareketlerin sonuçlarını birbirinden ayır.","Mevsimlerin uzaklıktan değil eksen eğikliği ve dolanımdan oluştuğunu bil.","Yerel saat farkıyla ortak saat uygulamasını karıştırmak."],
    "Atmosfer ve İklim":["Sıcaklık, basınç, rüzgâr, nem ve yağışı neden–sonuç zincirinde; iklim tiplerini grafikle öğren.","Hava durumu ile iklimi zaman ve alan ölçeğine göre ayır.","Yükselti, enlem ve denizellik etkilerini tek başına mutlak kural gibi kullanmak."],
    "İç Kuvvetler":["Orojenez, epirojenez, volkanizma ve depremi levha hareketleriyle ilişkilendir.","Dağ oluşumu ile kıta yükselme/alçalmasını farklı ölçeklerde değerlendir.","Her dağlık alanı volkanik kabul etmek."],
    "Dış Kuvvetler":["Akarsu, rüzgâr, buzul, dalga ve yer altı sularının aşındırma–biriktirme şekillerini iklimle bağla.","Aynı dış kuvvetin aşındırma ve biriktirme şekillerini karıştırma.","Yer şeklinin adından etken kuvveti iklim/zemin koşuluna bakmadan seçmek."],
    "Su-Toprak-Bitkiler":["Su döngüsü, toprak oluşumu ve bitki örtüsünü iklim, ana kaya ve yer şekilleriyle ilişkilendir.","Zonal, intrazonal ve azonal toprakların oluşum ölçütlerini ayır.","Bitki örtüsünü yalnız yağış miktarıyla açıklamak."],
    "Nüfus":["Nüfus dağılışı, yoğunluk, artış, yaş yapısı ve piramitleri doğal/beşerî etkenlerle yorumla.","Aritmetik, tarımsal ve fizyolojik yoğunluğun paydalarını ayır.","Nüfus miktarı yüksek ülkenin yoğunluğunu da kesin yüksek sanmak."],
    "Göç":["Göçleri iç/dış, gönüllü/zorunlu, geçici/sürekli olarak neden ve sonuçlarıyla sınıflandır.","Göç veren ve alan yerdeki etkileri ayrı sütunlarda düşün.","Bütün göçleri yalnız ekonomik nedenle açıklamak."],
    "Yerleşme":["Kır/kent, toplu/dağınık ve sürekli/geçici yerleşmeyi doğal ve ekonomik koşullarla bağla.","Yerleşme dokusu ile yerleşmenin ekonomik fonksiyonunu ayır.","Ev yapı malzemesini yalnız iklime bağlayıp yerel jeolojiyi göz ardı etmek."],
    "Türkiye'nin Yer Şekilleri":["Türkiye'nin genç oluşumu, yükselti, dağların uzanışı, platolar ve ovaları haritada öğren.","Kuzey–güney kıyıları ile Ege kıyılarında dağ uzanışının sonuçlarını karşılaştır.","Mutlak konum sonucunu özel konum sonucuyla karıştırmak."],
    "Ekonomik Faaliyetler":["Tarım, hayvancılık, sanayi, madencilik, enerji, hizmet ve turizmi yer seçimi faktörleriyle açıkla.","Üretim miktarı, verim, ekim alanı ve ticari değer kavramlarını ayrı oku.","Bir faaliyetin dağılışını tek bir doğal etkene bağlamak."],
    "Bölgeler":["Bölgeyi seçilen ölçüte göre oluşturulan değişebilir sınırlarla tanımla.","Doğal, beşerî, ekonomik ve işlevsel bölge ölçütlerini karıştırma.","Bölge sınırlarını idari sınırlar gibi kesin ve değişmez sanmak."],
    "Doğal Afetler":["Afet türünü tehlike, risk, kırılganlık ve alınacak önlemlerle birlikte değerlendir.","Afetin doğal olaydan farklı olarak insan ve sistemler üzerinde kayıp oluşturduğunu bil.","Her afet için yalnız olay sonrası müdahaleyi çözüm saymak."],
    "Nüfus Politikaları":["Artırıcı, azaltıcı ve niteliği geliştirici politikaları ülkenin nüfus yapısıyla ilişkilendir.","Politikanın uygulandığı dönem ile güncel nüfus ihtiyacını karıştırma.","Tek bir nüfus politikasını her ülke için uygun görmek."],
    "Şehirleşme":["Kentleşme hızını sanayileşme, göç, altyapı ve kent fonksiyonlarıyla yorumla.","Şehir nüfusunun artmasıyla planlı kentleşmenin aynı şey olmadığını bil.","Büyük nüfuslu her yerleşmeyi aynı ekonomik fonksiyonda saymak."],
    "Türkiye Ekonomisi":["Türkiye'de sektörleri dağılış, üretim, istihdam ve dış ticaret bağlantısıyla haritada öğren.","Mutlak üretim ile verimlilik/kişi başına değerleri ayır.","Güncel değişebilen veriyi kalıcı coğrafi ilke gibi ezberlemek."],
    "Ulaşım":["Ulaşım türlerini maliyet, hız, kapasite, topoğrafya ve ticaret koridorlarıyla karşılaştır.","Türkiye'de dağ uzanışı ve geçitlerin ulaşım yönüne etkisini haritada izle.","En hızlı ulaşım türünü her yük ve mesafe için en ekonomik saymak."],
    "Jeopolitik Konum":["Türkiye'nin boğazlar, enerji yolları, kıtalar ve komşu bölgeler açısından konumunu fırsat/risk dengesiyle değerlendir.","Jeopolitik önemin zamana göre değişebileceğini; matematik konumun değişmediğini bil.","Jeopolitik yorumu yalnız komşu sayısına indirgemek."],
    "Ülkeler ve Bölgeler":["Ülkeleri konum, kaynak, nüfus, ekonomi ve bölgesel örgütlerle karşılaştır.","Gelişmişlik, nüfus büyüklüğü ve doğal kaynak zenginliğini aynı ölçüt sanma.","Tek bir göstergeyle ülkenin gelişmişliğini kesinleştirmek."],
    "Çevre ve Toplum":["Kaynak kullanımı, çevresel etki, taşıma kapasitesi ve sürdürülebilirliği birlikte değerlendir.","Çevresel sorunun nedenini, sonucunu ve çözüm aracını farklı ölçeklerde ayır.","Teknolojinin her çevre sorununu yan etkisiz çözeceğini varsaymak."],
    "Küresel Ortam":["Küresel ticaret, kültür, ulaşım, iletişim ve çevre sorunlarını merkez–ağ–akış ilişkisiyle yorumla.","Küresel bağlantının bütün bölgelerde aynı sonucu doğurmadığını unutma.","Küreselleşmeyi yalnız ekonomik ticaret olarak görmek."],
    "Doğal Sistemler":["Atmosfer, hidrosfer, litosfer ve biyosfer süreçlerini enerji/madde akışıyla birbirine bağla.","Bir sistemdeki değişimin diğer sistemlere gecikmeli ve dolaylı etkilerini ara.","Doğal süreçleri birbirinden bağımsız yorumlamak."],
    "Beşerî Sistemler":["Nüfus, yerleşme, kültür, ekonomi ve siyasi örgütlenmeyi mekânsal dağılışla ilişkilendir.","Neden–sonuç yönünü ve ölçeği harita/grafik üzerinden kontrol et.","Korelasyonu tek başına nedensellik saymak."],
    "Türkiye Coğrafyası":["Türkiye'nin fiziki ve beşerî özelliklerini bölgesel farklarla, harita üzerinde bütünleştir.","Genel Türkiye özelliği ile yalnız belirli yörede görüleni ayır.","Bölge ezberini neden bilgisi olmadan yapmak."],
    "Küresel Ticaret":["Hammadde, üretim, pazar, lojistik ve ticaret yollarını küresel ağ üzerinde ilişkilendir.","İhracat miktarı ile dış ticaret dengesi ve katma değeri ayır.","Kaynağa sahip ülkenin üründe mutlaka en büyük ihracatçı olduğunu sanmak."],
    "Bölgeler ve Ülkeler":["Bölgesel birlikleri, ülkelerin ekonomik/siyasi özelliklerini ve dünya içindeki rollerini karşılaştır.","Örgüt üyeliği, coğrafi bölge ve kültür bölgesini aynı sınır kabul etme.","Güncel üyelikleri eski harita bilgisiyle kesin saymak."],

    /* Felsefe, psikoloji, sosyoloji, din */
    "Felsefeye Giriş":["Felsefi düşüncenin sorgulayıcı, tutarlı, eleştirel ve sistemli özelliklerini problem alanlarıyla ilişkilendir.","Felsefi soru ile bilimsel/olgusal soruyu amaç ve cevap biçimine göre ayır.","Her soyut soruyu felsefi soru kabul etmek."],
    "Bilgi Felsefesi":["Bilginin kaynağı, sınırı, ölçütü ve mümkünlüğü problemlerini temel yaklaşımlarla eşleştir.","Rasyonalizm, empirizm, kritisizm, septisizm ve dogmatizmi savlarına göre ayır.","Parçada geçen tek bir kavramdan filozof/yaklaşım seçmek."],
    "Varlık Felsefesi":["Varlığın ne olduğu, değişim, öz–görünüş ve madde–idea tartışmalarını yaklaşımlarla bağla.","Monizm, düalizm, plüralizm ile idealizm/materyalizmi farklı sınıflandırmalar olarak gör.","“Varlık vardır” ifadesini bütün ontolojik görüşlerin aynı şeyi savunduğu sanısıyla okumak."],
    "Ahlak Felsefesi":["İyi, özgürlük, sorumluluk, erdem ve evrensel ahlak yasası problemlerini ölçütleriyle incele.","Sonuç, ödev, haz ve erdem merkezli yaklaşımların gerekçelerini ayır.","Kendi ahlaki yargısını metnin savı yerine koymak."],
    "Sanat Felsefesi":["Güzellik, sanat eseri, sanatçı, alımlayıcı ve taklit/yaratma görüşlerini ayır.","Estetik yargının öznel yönüyle ortak ölçüt tartışmasını birlikte değerlendir.","Güzel olan her şeyi sanat eseri kabul etmek."],
    "Din Felsefesi":["Tanrı'nın varlığı, vahiy, iman–akıl, kötülük ve özgürlük problemlerini felsefi gerekçelerle ele al.","Teizm, deizm, panteizm, ateizm ve agnostisizmi Tanrı–evren ilişkisine göre ayır.","Din felsefesini dinî hüküm vermekle aynı etkinlik sanmak."],
    "Siyaset Felsefesi":["Devlet, iktidar, meşruiyet, adalet, hak ve özgürlük sorunlarını temel yaklaşımlarla ilişkilendir.","Olan siyasal düzeni betimlemekle olması gerekeni tartışmayı ayır.","Özgürlük ve eşitliği her görüşte aynı anlamda kullanmak."],
    "Psikoloji":["Davranış ve zihinsel süreçleri öğrenme, gelişim, bellek, algı ve kişilik başlıklarıyla bilimsel yöntem içinde ele al.","Korelasyon ile nedenselliği; duyum ile algıyı ayır.","Tek bir davranıştan kişilik veya hastalık tanısı çıkarmak."],
    "Sosyoloji":["Toplum, kurum, kültür, statü, rol, grup ve toplumsal değişmeyi ilişkisel düşün.","Toplumsal olgu ile bireysel örneği; statü ile rolü ayır.","Bir kültürün değerlerini evrensel ölçüt gibi kullanmak."],
    "Bilgi ve İnanç":["Doğru bilgi, iman, vahiy, akıl ve sorumluluk ilişkisini kaynak ve amaçlarıyla değerlendir.","Bilgi ile zannı; inanç ile kör taklidi aynı şey sayma.","Parçadaki ana ölçüt yerine kişisel kabulü cevap yapmak."],
    "İslam ve İbadet":["İbadetlerin amaç, şart, bireysel ve toplumsal etkilerini birlikte öğren.","İbadetin biçimsel şartı ile ahlaki amacını birbirinden koparma.","Bütün ibadetleri yalnız bireysel faydayla açıklamak."],
    "Ahlak ve Değerler":["Ahlaki tutumları niyet, davranış, hak ve sorumluluk bağlamında değerlendir.","Evrensel değer ile kültürel uygulama örneğini ayır.","İyi niyetin her sonucu tek başına meşru kıldığını varsaymak."],
    "Allah-İnsan İlişkisi":["İrade, sorumluluk, dua, tevekkül ve kader kavramlarını insanın çabasıyla birlikte yorumla.","Tevekkülün önlem ve emekten sonra güvenmek olduğunu unutma.","Kader inancını insan sorumluluğunu kaldıran bir gerekçe sanmak."],
    "Hz. Muhammed":["Hz. Muhammed'in peygamberlik, örneklik, tebliğ ve toplumsal liderlik yönlerini kaynak bağlamıyla öğren.","Tarihsel olay ile o olaydan çıkarılan evrensel ilkeyi ayır.","Bir rivayeti bağlamından koparıp genel hüküm hâline getirmek."],
    "Vahiy ve Akıl":["Vahiy, akıl, duyular ve doğru haberin bilgi edinmedeki yerini birlikte değerlendir.","Akıl ile vahyi rakip kaynaklar gibi sunan seçeneklere dikkat et.","Metnin akla verdiği işlevi yalnız ezber olarak yorumlamak."],
    "Din-Kültür-Medeniyet":["Dinin kültür ve medeniyete etkisini sanat, bilim, hukuk ve sosyal hayat örnekleriyle ilişkilendir.","Dinin temel ilkesiyle tarihsel/kültürel yorumunu ayır.","Her kültürel geleneği dinin değişmez hükmü saymak."],
    "Güncel Dinî Meseleler":["Güncel meseleleri temel amaçlar, zararın önlenmesi, hak, sorumluluk ve güvenilir bilgi ölçütleriyle değerlendir.","Kişisel kanaat, bilimsel veri ve dinî ilkeyi birbirine karıştırma.","Yeni bir durumu yalnız ad benzerliğiyle eski hükme eşitlemek."],
    "Dinler Tarihi":["Dinleri inanç, ibadet, kutsal metin ve tarihsel gelişim başlıklarıyla karşılaştır.","Mezhep, din ve kültürel gelenek kavramlarını ayır.","Benzer ritüellerden dinlerin tüm öğretilerinin aynı olduğu sonucunu çıkarmak."],
    "Kur'an ve Yorumu":["Ayetleri bağlam, ana mesaj, temel kavram ve yorum ilkeleriyle değerlendir.","Meal ile tefsirin kapsamını; evrensel ilke ile tarihsel örneği ayır.","Tek bir ifadeyi bağlamdan koparıp parçanın ana düşüncesi yapmak."],
    "İslam ve Bilim":["Bilgiye verilen değer, bilimsel faaliyetler ve Müslüman bilginlerin katkılarını alanlarıyla eşleştir.","Bilimsel katkının üretildiği dönem ve bilginin yaşadığı coğrafyayı karıştırma.","Bilim–din ilişkisini tek bir tarihsel olayla genellemek."],
    "İslam Düşüncesinde Yorumlar":["İtikadi, fıkhi ve tasavvufi yorumları ortaya çıkış nedeni ve alanıyla ayır.","Yorum farklılığını dinin temel kaynaklarıyla özdeşleştirme.","Mezhep ve yorumları ayrı dinler gibi görmek."],
    "Yaşayan Dinler":["Günümüzde yaşayan dinleri temel inanç, ibadet, metin ve coğrafi yayılışlarıyla karşılaştır.","Dinî öğretinin özü ile bölgesel uygulama biçimini ayır.","Coğrafi yakınlıktan inanç benzerliği sonucu çıkarmak."],

    /* Edebiyat */
    "Şiir Bilgisi":["Nazım birimi, ölçü, uyak, redif, tema ve şiir türünü metin üzerinde belirle.","Uyak ses benzerliği, redif görev ve anlamı aynı ek/sözcük tekrarına dayanır.","Yalnız yazılışa bakarak redif olan bölümü uyağa katmak."],
    "Söz Sanatları":["Benzetme, eğretileme, kişileştirme, konuşturma, karşıtlık ve diğer sanatları metindeki ilişkiyle tanı.","Aynı dizede birden fazla sanat bulunabileceğini; sorunun istediğini ayır.","İnsan dışı varlığa her eylem verildiğinde otomatik kişileştirme saymak."],
    "Halk Edebiyatı":["Anonim, âşık ve tekke kollarını nazım biçimi, ölçü, dil ve temsilcileriyle karşılaştır.","Koşma, semai, varsağı ve destanı biçim/tema özellikleriyle ayır.","Halk edebiyatındaki her ürünü anonim kabul etmek."],
    "Divan Edebiyatı":["Nazım biçimleri, aruz, mazmun, dil ve sanatçı–eser ilişkilerini tür özellikleriyle öğren.","Gazel, kaside, mesnevi ve rubainin nazım birimi, uyak ve konu farklarını ayır.","Aynı nazım birimini kullanan biçimleri birbirinin yerine koymak."],
    "Tanzimat":["Birinci ve ikinci dönem sanat anlayışını dil, tema, toplumculuk ve sanatçılarıyla karşılaştır.","Sanatçıların farklı türlerdeki eserlerini ve dönem içindeki değişimlerini kontrol et.","“Toplum için sanat” ilkesini bütün Tanzimat sanatçılarına aynı ölçüde uygulamak."],
    "Servet-i Fünun":["Ağır dil, bireysel temalar, Batılı teknik ve sanat için sanat anlayışını sanatçı–eserlerle bağla.","Servet-i Fünun ile Fecr-i Ati benzerliklerini ve ayrıldığı noktaları ayır.","Dönemin şiir ve roman özelliklerini tek kalıp gibi kullanmak."],
    "Milli Edebiyat":["Yeni Lisan, sade Türkçe, millî kaynaklar ve Anadolu yönelimini temsilci/eserlerle öğren.","Dönem içinde farklı sanat anlayışlarının eş zamanlı bulunabildiğini unutma.","1911 sonrası yazan her sanatçıyı Milli Edebiyatçı saymak."],
    "Cumhuriyet Dönemi":["Şiir, roman, hikâye ve tiyatrodaki farklı topluluk/anlayışları tema, dil ve teknikle karşılaştır.","Aynı sanatçının dönem içinde farklı anlayışlara yaklaşabileceğini kontrol et.","Cumhuriyet dönemi eserlerini tek bir sanat anlayışı altında toplamak."],
    "Roman-Hikaye":["Olay, durum, anlatıcı, bakış açısı, zaman, mekân ve anlatım tekniklerini metinden belirle.","Yazar ile anlatıcıyı; kahraman anlatıcı ile gözlemci/ilahi bakış açısını ayır.","Birinci kişi kullanılan her metni öz yaşam öyküsü sanmak."],
    "Tiyatro":["Geleneksel ve modern tiyatroyu yapı, sahne, tip/karakter ve tür özellikleriyle karşılaştır.","Trajedi, komedi ve dramın klasik kurallarını; meddah, orta oyunu, Karagöz yapılarını ayır.","Göstermeye bağlı her metni modern tiyatro kabul etmek."],

    /* YDT */
    "Kelime Bilgisi":["Sözcüğü tek karşılıkla değil eşdizim, edat, sözcük türü ve bağlam içindeki anlamıyla öğren.","Olumlu/olumsuz çağrışım, yakın anlam ve false friend ayrımlarını cümle içinde kontrol et.","Türkçedeki ilk karşılığı seçeneğe taşıyıp bağlam uyumunu denetlememek."],
    "Dil Bilgisi":["Zaman, kip, çatı, bağlaç, relative clause, modal ve preposition ipuçlarını cümlenin zaman/anlam çizgisiyle çöz.","Tek boşluğa değil özne–yüklem uyumu ve cümlenin iki tarafı arasındaki ilişkiye bak.","Yalnız biçimce doğru olan seçeneği anlamı kontrol etmeden işaretlemek."],
    "Cloze Test":["Paragrafın ana konusu ve cümleler arası bağ kurulduktan sonra boşluğun sözcük türü/anlam ihtiyacını belirle.","Her boşluğu bağımsız çözme; önceki ve sonraki cümlede zamir, bağlaç ve zaman uyumunu izle.","İlk uygun görünen seçeneği seçip paragrafın tamamını yeniden okumamak."],
    "Cümle Tamamlama":["Verilen bölümde sebep, sonuç, karşıtlık, koşul ve zaman ilişkisini tespit ederek devamı seç.","Özne, zamir, zaman ve anlam yönünün iki parçada tutarlı olmasını ara.","Konu benzerliğini mantıksal bağ için yeterli saymak."],
    "Çeviri":["Ana yüklem, özne, yan cümlecikler, bağlaç ve niteleyicileri iskelet hâlinde eşleştir.","Zaman, olumsuzluk, edilgenlik, miktar ve olasılık anlamının hedef dilde korunmasını denetle.","Sözcük sözcük aynı görünen ama cümle ilişkisini değiştiren seçeneği seçmek."],
    "Anlamca Yakın Cümle":["Ana önerme, tutum, kesinlik derecesi ve neden–sonuç ilişkisini değişmeden taşıyan seçeneği ara.","Some/all, may/must, increase/decrease gibi kapsam ve kesinlik değişikliklerine dikkat et.","Aynı anahtar sözcükleri içerdiği için anlamı daraltan/genişleten seçeneği doğru sanmak."],
    "Diyalog Tamamlama":["Konuşmacıların niyeti, ton, soru–cevap biçimi ve önceki/sonraki replik bağlantısını izle.","Zamir göndergesi ve verilen cevabın hangi soruyu gerektirdiğini kontrol et.","Dil bilgisi doğru ama konuşma işlevine uymayan cümleyi seçmek."],
    "Duruma Uygun İfade":["Rol, amaç, resmiyet düzeyi ve iletişim eylemini—öneri, özür, uyarı, rica—belirle.","Söylenecek kişinin kim olduğu ve durumun zamanını seçenekte koru.","Genel olarak mantıklı ama belirtilen amaca hizmet etmeyen ifadeyi seçmek."],
    "Anlatım Bütünlüğü":["Paragrafın konusu, bakış açısı, zaman çizgisi ve bağlaç zincirini bozan cümleyi ara.","Yeni konu açan cümleyle önceki düşünceyi örnekleyen cümleyi ayır.","Bilinmeyen sözcük içeren cümleyi otomatik olarak bütünlüğü bozan cümle saymak."]
  };

  const SUBJECT_ALIASES={
    "Matematik (AYT)":"math","Matematik":"math","Geometri (AYT)":"geometry","Geometri":"geometry",
    "Fizik (AYT)":"physics","Fizik":"physics","Kimya (AYT)":"chemistry","Kimya":"chemistry",
    "Biyoloji (AYT)":"biology","Biyoloji":"biology","Tarih (AYT)":"history","Tarih-2":"history","Tarih":"history",
    "Coğrafya (AYT)":"geography","Coğrafya-2":"geography","Coğrafya":"geography","Felsefe Grubu":"philosophy","Felsefe":"philosophy",
    "Din Kültürü (AYT)":"religion","Din Kültürü":"religion","Türkçe":"turkce","Edebiyat":"literature","Yabancı Dil":"ydt"
  };

  const SPECIAL={
    "Geometri|Temel Kavramlar":["Doğru, ışın, açı, açıortay, paralellik ve diklik sembollerini şekil üzerinde doğru göster.","Tümler–bütünler ile ters/yöndeş/iç ters açı ilişkilerini çizgi koşullarına göre kullan.","Paralellik verilmeden yöndeş veya iç ters açı eşitliği kurmak."],
    "Felsefe Grubu|Mantık":["Kavram, önerme, çıkarım ve kıyas yapısını geçerlilik–doğruluk ayrımıyla incele.","Bir çıkarımın geçerli olmasıyla öncül/sonucunun gerçek hayatta doğru olmasını aynı sayma.","Sonuç doğru olduğu için akıl yürütmeyi otomatik geçerli kabul etmek."],
    "Yabancı Dil|Paragraf":["Ana fikir, yazarın tutumu, gönderim ve çıkarım sorularında kanıtı metinde bul.","Bilinmeyen tek sözcüğe takılma; bağlaçlar ve tekrar eden kavramlarla paragraf haritası çıkar.","Kendi genel bilgisini metnin söylediği şeymiş gibi seçeneğe taşımak."],
    "Coğrafya (AYT)|Ekosistem":["Ekosistemlerin enerji akışı, madde döngüsü ve insan etkisini mekânsal ölçekte yorumla.","Biyom, habitat ve ekosistem kavramlarını ölçek ve işlev bakımından ayır.","Aynı iklimde her yerde aynı ekosistemin değişmeden bulunduğunu sanmak."],
    "Biyoloji (AYT)|Üreme":["İnsanda üreme sistemi, gamet oluşumu, hormonal kontrol, döllenme ve gelişimi sırayla öğren.","Ovulasyon, döllenme ve implantasyonun yer/zamanını birbirinden ayır.","Menstrual döngü hormonlarının artış–azalış sırasını ters kurmak."]
  };

  function clean(value){return String(value==null?"":value).trim();}
  function profileFor(subject){return PROFILES[SUBJECT_ALIASES[clean(subject)]]||PROFILES.turkce;}
  function topicNote(subject,topic){return SPECIAL[clean(subject)+"|"+clean(topic)]||NOTES[clean(topic)]||null;}
  function resourcesFor(exam){return exam==="YDT"?[SOURCES.mebYks,SOURCES.osym,SOURCES.ogm]:[SOURCES.mebTests,SOURCES.mebYks,SOURCES.osym,SOURCES.ogm];}
  function guideFor(exam,subject,topic){
    exam=clean(exam)||"TYT";subject=clean(subject)||"Ders";topic=clean(topic)||"Konu";
    const p=profileFor(subject),n=topicNote(subject,topic);
    const specific=!!n;
    const core=n?n[0]:topic+" konusunda tanımları, temel ilişkileri ve soru kökünde verilen koşulları birlikte ele al.";
    const watch=n?n[1]:topic+" sorularında birbirine yakın kavramları karşılaştırmalı çalış ve kapsam değişikliklerini kontrol et.";
    const mistake=n?n[2]:topic+" bilgisini koşullarını kontrol etmeden her soruya aynı biçimde uygulamak.";
    return {
      exam,subject,topic,specific,
      important:[core,p.important],
      attention:[watch,p.attention],
      mistakes:[mistake,p.mistake],
      study:["Bugün "+topic+" için 10 dakikalık özet çıkar; bir kolay, bir orta ve bir zor örnekte aynı kuralın nasıl değiştiğini yaz.",p.study],
      checklist:[
        topic+" konusunu bir örneğe bakmadan üç cümlede açıklayabiliyor musun?",
        "Bir soruda verilen bilgi, istenen ve çözüm koşulunu birbirinden ayırabiliyor musun?",
        "Yanlış seçenekteki hatayı veya eksik koşulu adlandırabiliyor musun?"
      ],
      sources:resourcesFor(exam),
      note:"Bu rehber MEB konu/kazanım çerçevesi ve yayımlanmış resmî YKS sorularındaki beceri türleri temel alınarak hazırlanmış kısa çalışma özetidir; soru tahmini veya çıkma garantisi değildir."
    };
  }
  function coverage(curriculum){
    let total=0,specific=0,missing=[];
    ["TYT","AYT","YDT"].forEach(exam=>(curriculum?.[exam]||[]).forEach(subject=>(subject.topics||[]).forEach(topic=>{total++;if(topicNote(subject.name,topic))specific++;else missing.push(exam+" · "+subject.name+" · "+topic);})));return {total,specific,missing};
  }

  window.YKSTopicGuides={guideFor,coverage,sources:SOURCES,notes:NOTES};
})();
