const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');

test('Öğrenme Laboratuvarı v3 paragraf aracını kaldırır, YKS periyodik katmanını ve kronoloji timeline yapısını kurar',()=>{
  const file=path.join(root,'modules/learning-lab-v3.js');
  assert.equal(fs.existsSync(file),true);
  const s=fs.readFileSync(file,'utf8');
  const stability=fs.readFileSync(path.join(root,'modules/stability.js'),'utf8');
  const sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');
  assert.match(s,/v320TabParagraph/);
  assert.match(s,/v320PanelParagraph/);
  assert.match(s,/\.remove\(\)/);
  assert.match(s,/Periyodik Tablo/);
  assert.match(s,/Kronoloji/);
  assert.match(s,/Bilim Kartları/);
  assert.match(s,/Biyoloji/);
  assert.match(s,/Fizik/);
  assert.match(s,/deepDives/);
  assert.match(s,/Sık hata/);
  assert.match(s,/YKS taktiği/);
  assert.match(s,/Atom çapı/);
  assert.match(s,/İyonlaşma enerjisi/);
  assert.match(s,/Elektronegatiflik/);
  assert.match(s,/Metalik karakter/);
  assert.match(s,/Ametalik karakter/);
  assert.match(s,/YKS trend paneli/);
  assert.match(s,/v4PeriodicSetType/);
  assert.match(s,/v4PeriodicToggleYks/);
  assert.match(s,/v4PeriodicToggleFavorites/);
  assert.match(s,/v4ElementYksDetail/);
  assert.match(s,/Kronoloji timeline/);
  assert.match(s,/v4TimelineOverview/);
  assert.match(s,/v4TimelineChooseEra/);
  assert.match(s,/decorateTimeline/);
  assert.match(s,/v4-history-timeline/);
  assert.match(s,/Sonuç \/ etkisi/);
  assert.match(s,/bindMainTabs/);
  assert.match(s,/removeAttribute\("onclick"\)/);
  assert.match(s,/addEventListener\("click",\(\)=>setTab\(key\)\)/);
  assert.match(s,/version:"3\.4\.0"/);
  assert.match(stability,/learning-lab-v2\.js\?v=4\.1\.0-r24/);
  assert.match(stability,/learning-lab-v3\.js\?v=4\.1\.0-r28/);
  assert.match(stability,/motivation-quotes-v1\.js\?v=4\.1\.0-r2/);
  assert.match(sw,/learning-lab-v2\.js\?v=4\.1\.0-r24/);
  assert.match(sw,/learning-lab-v3\.js\?v=4\.1\.0-r28/);
  assert.match(sw,/motivation-quotes-v1\.js\?v=4\.1\.0-r2/);
  assert.match(sw,/motivation-quotes-v2\.css\?v=4\.1\.0-r1/);
  assert.match(sw,/ui-polish-progress-v2\.css\?v=4\.1\.0-r1/);
  assert.match(sw,/const CACHE="yks-core-v4\.1\.0-r36"/);
  assert.match(sw,/yks-core-v4\.1\.0-r35/);
  assert.match(sw,/yks-core-v4\.1\.0-r34/);
  assert.match(sw,/yks-core-v4\.1\.0-r33/);
  assert.match(sw,/yks-core-v4\.1\.0-r32/);
  assert.match(sw,/yks-core-v4\.1\.0-r31/);
  assert.match(sw,/yks-core-v4\.1\.0-r28/);
  assert.match(sw,/yks-core-v4\.1\.0-r26/);
  assert.match(sw,/yks-core-v4\.1\.0-r25/);
  assert.match(sw,/yks-core-v4\.1\.0-r24/);
  assert.match(sw,/yks-core-v4\.1\.0-r23/);
  assert.match(sw,/yks-core-v4\.1\.0-r22/);
});

test('Öğrenme Laboratuvarı v2 element blok hesabında sabit değişkene yeniden atama yapmaz',()=>{
  const s=fs.readFileSync(path.join(root,'modules/learning-lab-v2.js'),'utf8');
  assert.match(s,/function blockOf\(z\)\{const group=groupOf\(z\)/);
  assert.match(s,/const g=Number\(group\)/);
  assert.doesNotMatch(s,/const g=groupOf\(z\)[^}]*g=Number\(g\)/);
});