import {ATLAS_GROUPS, ATLAS_TOPICS, type AtlasGroup, type AtlasTopic} from "../data/biology-atlas.ts";
import {ATLAS_GUIDES} from "../data/biology-atlas-guides.ts";
import {answerAtlas, filterAtlas, getAtlasOrgan} from "../domain/biology-atlas-service.ts";
import {atlasDiagram, atlasEscape as esc} from "./biology-atlas-diagrams.ts";

export type LessonView="steps"|"details"|"quiz";
const groupNotes=["Sinirden dolaşıma, organlar nasıl birlikte çalışır?","DNA'daki bilgi hücrenin işine nasıl dönüşür?","Hücre enerjiyi nasıl dönüştürür ve kullanır?","Kökten çiçeğe yapı, taşıma ve üreme.","Bireyden ekosisteme canlılar arası bağlantılar."];
const groupArt=[
  '<path d="M89 39C62 4 19 32 39 69L89 109L140 68C159 29 114 5 89 39Z"/><path d="M38 64H67L78 47L91 83L107 61H140" class="atlas-art-line"/>',
  '<path d="M59 19C133 42 36 76 112 108M112 19C36 42 133 76 59 108" class="atlas-art-line"/><path d="M64 31H107M68 49H105M64 72H107M68 92H105" class="atlas-art-line"/>',
  '<ellipse cx="87" cy="64" rx="65" ry="37"/><path d="M39 65C48 21 67 99 79 43S103 98 116 55S137 78 130 79" class="atlas-art-line"/>',
  '<path d="M87 112V52M87 64Q79 10 130 16Q139 56 87 64ZM85 89Q42 92 37 53Q78 48 85 89Z"/>',
  '<circle cx="54" cy="44" r="19"/><circle cx="124" cy="48" r="19"/><circle cx="89" cy="99" r="19"/><path d="M77 44H101M113 68L102 80M71 81L61 65" class="atlas-art-line"/>'
];
export function atlasGroupArt(group:AtlasGroup):string {
  return `<svg viewBox="0 0 178 128" aria-hidden="true" class="atlas-group-art">${groupArt[ATLAS_GROUPS.indexOf(group)]}</svg>`;
}
export function atlasOverview(group:AtlasGroup|"all",query:string):string {
  const all=group==="all"&&!query;
  return `<header class="atlas-overview-head"><span class="atlas-kicker">${all?"01 · BİR ALAN SEÇ":"02 · BİR KONU SEÇ"}</span><h3>${all?"Neyi keşfetmek istersin?":query?"Arama sonuçları":esc(group)}</h3><p>${all?"Önce bir alan seç. Her konuyu görsel üzerinde öğren, ayrıntısını aç ve kendini sına.":"Bir konuya odaklan; ayrıntıları ihtiyacın olduğunda aç."}</p>${!all?'<button type="button" class="atlas-back" data-atlas-action="overview">← Bütün alanlar</button>':""}</header>`+
    (all?`<div class="atlas-group-grid">${ATLAS_GROUPS.map((name,i)=>`<button type="button" class="atlas-group-card atlas-group-${i}" data-atlas-action="group" data-id="${esc(name)}">${atlasGroupArt(name)}<span><small>${ATLAS_TOPICS.filter(t=>t.group===name).length} GÖRSEL KONU</small><b>${esc(name)}</b><span>${groupNotes[i]}</span><em>Keşfet →</em></span></button>`).join("")}</div><div class="atlas-learning-route"><span>1 · Görseli keşfet</span><span>2 · Bağlantıyı öğren</span><span>3 · Kendini sına</span></div>`:
    `<div class="atlas-topic-grid">${filterAtlas(query,group).map((t,i)=>`<button type="button" data-atlas-action="topic" data-id="${t.id}" class="atlas-topic-card"><span class="atlas-topic-number">${String(i+1).padStart(2,"0")}</span><span><small>${esc(t.group)}</small><b>${esc(t.title)}</b><span>${esc(ATLAS_GUIDES[t.id]!.goal)}</span><em>${t.steps.length} görsel durak · Ayrıntılı anlatım →</em></span></button>`).join("")||'<p class="atlas-empty">Bu aramada konu bulunamadı. Farklı bir sözcük deneyebilirsin.</p>'}</div>`);
}
export function atlasLesson(t:AtlasTopic,state:{step:number;view:LessonView;picked:number|null;labels:boolean;wide:boolean}):string {
  const {step,view,picked,labels,wide}=state,practice=view==="quiz",guide=ATLAS_GUIDES[t.id]!;
  const result=picked===null?null:answerAtlas(t,picked),node=t.steps[step]!;
  return `<button type="button" class="atlas-back" data-atlas-action="group" data-id="${esc(t.group)}">← ${esc(t.group)}</button><header class="atlas-lesson-head"><div><span class="atlas-kicker">KONU ATLASI · ODAKLI ÖĞRENME</span><h3>${esc(t.title)}</h3><p>${esc(t.intro)}</p></div></header>`+
    `<div class="atlas-lesson-tabs" role="group" aria-label="Öğrenme biçimi"><button type="button" data-atlas-action="lesson-view" data-id="steps" aria-pressed="${view==="steps"}">1 · Adım adım</button><button type="button" data-atlas-action="lesson-view" data-id="details" aria-pressed="${view==="details"}">2 · Ayrıntılı anlatım</button><button type="button" data-atlas-action="practice" aria-pressed="${practice}">3 · Kendini sına</button></div>`+
    `<div class="atlas-workbench ${wide?"atlas-wide":""}"><figure class="atlas-figure ${labels?"":"atlas-hide-labels"}"><div class="atlas-figure-tools">${practice?' <span>İpuçları gizli · Numaradan yanıtla</span>':`<button type="button" data-atlas-action="topic-labels" aria-pressed="${labels}">${labels?"Etiketleri gizle":"Etiketleri göster"}</button>`}<button type="button" data-atlas-action="wide" aria-pressed="${wide}">${wide?"Normal görünüm":"Görseli büyüt"}</button></div>${atlasDiagram(t,step,practice,result?.answer??null)}<figcaption>Öğretici şema · Ölçekli çizim değildir. Numaralara veya aşağıdaki yapı düğmelerine dokun.</figcaption></figure>`+
    `<aside class="atlas-explanation" aria-live="polite">${practice?`<span class="atlas-kicker">Görsel soru</span><h4>${esc(t.quiz.prompt)}</h4><p>Şemadaki numaralardan uygun olanı seç.</p>${result?`<div class="atlas-feedback ${result.correct?"is-correct":"is-wrong"}" role="status"><b>${result.correct?"Doğru ✓":"Birlikte düzeltelim"}</b><p>Doğru nokta: ${result.answer+1} · ${esc(t.steps[result.answer]![0])}</p><p>${esc(result.explanation)}</p></div><button type="button" data-atlas-action="retry-quiz">Yeniden dene</button>`:""}`:
    `<span class="atlas-kicker">${step+1} / ${t.steps.length} · Yapı ve işlev</span><h4>${esc(node[0])}</h4><p>${esc(node[1])}</p><div class="atlas-step-progress" aria-hidden="true">${t.steps.map((_,i)=>`<span class="${i===step?"is-current":""}"></span>`).join("")}</div><div class="atlas-step-nav"><button type="button" data-atlas-action="previous" ${step===0?"disabled":""}>← Önceki</button><button type="button" data-atlas-action="next" ${step===t.steps.length-1?"disabled":""}>Sonraki →</button></div>`}</aside></div>`+
    `<div class="atlas-step-list" role="group" aria-label="${practice?"Yanıt noktaları":"Şema adımları"}">${t.steps.map(([label],i)=>`<button type="button" data-atlas-step="${i}" aria-pressed="${practice?picked===i:step===i}"><span>${i+1}</span>${practice?"Nokta "+(i+1):esc(label)}</button>`).join("")}</div>`+
    (view==="details"?`<section class="atlas-deep-dive" aria-label="Ayrıntılı konu anlatımı"><div class="atlas-goal"><span class="atlas-kicker">ÖĞRENME HEDEFİ</span><p>${esc(guide.goal)}</p></div><div class="atlas-detail-grid"><article><span class="atlas-kicker">NASIL İŞLER?</span><h4>Mekanizmayı bağla</h4><p>${esc(guide.mechanism)}</p></article><article><span class="atlas-kicker">BİR ÖRNEKLE</span><h4>Bilgiyi kullan</h4><p>${esc(guide.example)}</p></article></div><div class="atlas-comparison"><h4>Yan yana düşün</h4><table><caption class="atlas-sr-only">${esc(t.title)}: temel ayrımlar</caption><thead><tr><th scope="col">Yapı / kavram</th><th scope="col">Ayırt edici ilişki</th></tr></thead><tbody>${guide.compare.map(([key,value])=>`<tr><th scope="row">${esc(key)}</th><td>${esc(value)}</td></tr>`).join("")}</tbody></table></div><div class="atlas-takeaway"><b>Aklında kalsın</b><p>${esc(guide.takeaway)}</p></div></section>`:"")+
    `${!practice||result?`<div class="atlas-trap"><b>AYT'de karıştırma</b><p>${esc(t.trap)}</p></div>`:""}`+
    (!practice&&t.models.length?`<div class="atlas-related"><span>Yapıları organın üzerinde de incele</span>${t.models.map(id=>`<button type="button" data-atlas-action="organ-detail" data-id="${id}">${esc(getAtlasOrgan(id)!.name)} · Yapılar ↗</button>`).join("")}</div>`:"");
}
