export const LESSONS = [
  {
    id: "groups", number: "01", title: "Kelime grupları", subtitle: "Kelimelerin arasındaki bağı gör.", minutes: "2–3 dakika",
    explanation: "Bir cümlede anlam çoğu zaman tek bir kelimede değil, yan yana duran kelimelerin ilişkisindedir. Aşağıdaki cümleyi önce tek kelimelerle, ardından 2–4 kelimelik bloklarla oku. Her bloğu küçük bir düşünce olarak ele al; bütün satırı tek bakışta okumaya çalışma.",
    instructions: "İki görünümü karşılaştır. Sonra grupları sırayla takip et ve metne bakmadan ana fikri seç. Cümleyi bir kez de kendi hızında oku; hangi ayrımın anlamı daha iyi taşıdığına dikkat et.",
    groups: ["Düzenli kısa tekrarlar", "bilgiyi canlı tutabilir;", "tek bir uzun çalışma", "her öğrenci için", "aynı etkiyi sağlamayabilir."],
    question: "Bu cümlenin ana fikri hangisi?", options: ["Yalnız uzun çalışmalar işe yarar.", "Kısa ve düzenli tekrarlar yararlı olabilir.", "Tekrar yapmadan bilgiler kalıcı olur."], answer: 1,
    reflection: "Kendi kitabından iki cümle seç. Anlamı bölmeden 2–4 kelimelik kümelere ayır ve yaklaşık bir dakika oku. Uzun veya yeni bir sözcükte yavaşlamak normaldir."
  },
  {
    id: "returns", number: "02", title: "Geri dönüşleri fark et", subtitle: "Gereksiz tekrarı, gerekli kontrolden ayır.", minutes: "2–3 dakika",
    explanation: "Bazı cümleleri anlamak için yeniden okumak gerekir. Buradaki amaç bunu yasaklamak değil, anladığın satıra alışkanlıkla dönüp dönmediğini fark etmek. İlk geçişte ‘Yazar ne söylüyor?’ sorusuna odaklan. Anlam koparsa yeniden bakmak doğru bir tercihtir.",
    instructions: "Metni satır satır aç. Önceki satır gizlendiğinde ana fikri aklında tut. Gerekirse ‘Önceki satıra bak’ düğmesini kullan; dönüş sayısı yalnızca farkındalık içindir, ceza değildir.",
    groups: ["Bir okul, öğrencilerin dinlenmesi için bahçesine küçük bir okuma köşesi kurdu.", "Öğrenciler önce köşenin yalnız kitap okumak için kullanılacağını düşündü.", "Oysa öğretmenler sessizce düşünmenin de bu alanın amacı olduğunu anlattı.", "Böylece köşe, üretken olmak zorunda kalmadan mola verilebilen bir yer oldu."],
    question: "Okuma köşesinin asıl işlevi nedir?", options: ["Daha fazla ödev yaptırmak.", "Yalnız kitap sayısını artırmak.", "Okumaya ve sessizce dinlenmeye alan açmak."], answer: 2,
    reflection: "Bir sonraki paragrafta geri döndüğünde nedenini adlandır: ‘Dikkatim dağıldı’ mı, ‘Yeni bir kavram vardı’ mı? Bir dakika boyunca yalnız fark etmeyi dene. Gerekli geri dönüşleri ortadan kaldırmaya çalışma."
  },
  {
    id: "focus", number: "03", title: "Odak alanını genişlet", subtitle: "Merkezde kal, çevredeki kelimeleri fark et.", minutes: "2–3 dakika",
    explanation: "Kısa kelime gruplarıyla merkez ve çevre farkındalığını çalışabilirsin. Bu alıştırma bütün sayfayı tek bakışta okuma vaadi taşımaz. Rahat bir mesafede dur, ortadaki sözcüğe bakarken yanındaki sözcükleri de fark etmeye çalış. Zorlanırsan gösterimi yeniden aç.",
    instructions: "‘Kelimeleri göster’ düğmesine bas. Ortadaki sözcüğe bak; sol ve sağ sözcüğü fark et. Üç kısa turdan sonra son gördüğün sağ sözcüğü seç. Acele etmek yerine net algılamayı önemse.",
    rounds: [["sakin", "bir", "sabah"], ["küçük", "bir", "adım"], ["yeni", "bir", "başlangıç"]],
    question: "Son turda merkezin sağında hangi kelime vardı?", options: ["başlangıç", "yeni", "adım"], answer: 0,
    reflection: "Kısa bir satırda iki veya üç doğal durak seç. Bir dakika boyunca bu durakları izle. Boynunu ve gözlerini zorlamadan çalış; daha geniş alanda bulanıklık oluyorsa kelime grubunu küçült."
  },
  {
    id: "voice", number: "04", title: "İç seslendirmeyi yönet", subtitle: "İç sesi susturmak yerine akıcı bir ritim kur.", minutes: "2–3 dakika",
    explanation: "Okurken kelimeleri içinden duymak olağandır ve anlamaya yardımcı olabilir. Amaç iç sesi tamamen susturmak değildir. Bildiğin bir metinde gereksiz duraklamaları azaltmayı dene; zor bir kavramda ise düşünmeye zaman ayır. Ses, ritim ve anlama aynı kişide bile metne göre değişir.",
    instructions: "Aşağıdaki kısa metni rahat bir ritimle takip et. Her grupta anlamı alıp sıradakine geç. Sonunda ana fikri seç; anlamadıysan daha yavaş tekrarla. Hızlı görünmek için kelime atlama.",
    groups: ["Yeni bir alışkanlık", "küçük adımlarla gelişir.", "Her gün ayırdığın", "kısa bir çalışma zamanı", "başlamayı kolaylaştırır.", "Asıl değer", "tek seferde çalışmakta değil,", "sürdürülebilir bir ritimdedir."],
    question: "Metin hangi yaklaşımı öneriyor?", options: ["İç sesi tamamen susturmayı.", "Sürdürülebilir küçük adımlarla ilerlemeyi.", "Anlamasan da hızlanmayı."], answer: 1,
    reflection: "Bir dakika boyunca rahat bir metin oku; sonra ana fikri tek cümleyle anlat. Bunu yapamıyorsan ritmi düşür. Egzersizlerde başlangıç için 150 veya 200 kelime/dakikayı deneyebilir, gerektiğinde kendi hızına dönebilirsin."
  }
];

// Original practice passages. Question answers depend only on the text; no outside knowledge is required.
export const PASSAGES = [
  {
    id: "library", title: "Bir kütüphanenin değişen sesi", topic: "Toplum ve mekân", difficulty: "medium",
    text: "Mahalle kütüphanesi yenileneceği zaman ilk öneri daha fazla raf eklemek oldu. Görevliler ise karar vermeden önce ziyaretçileri dinlemeyi seçti. Öğrenciler sessiz masalar, küçük çocuklarıyla gelenler birlikte okuyabilecekleri bir köşe, yaşlı ziyaretçiler de rahat oturabilecekleri yerler istiyordu. Bu görüşmeler, tek bir düzenlemenin herkesin ihtiyacını karşılamayacağını gösterdi. Sonunda kütüphane farklı kullanım alanlarına ayrıldı. Sessiz bölüm korunurken girişe sohbet edilebilen küçük bir alan eklendi. Başlangıçta bazı ziyaretçiler bu değişikliğin kütüphaneyi gürültülü hâle getireceğinden kaygılandı. Ancak alanların açık biçimde ayrılması, kullanıcıların birbirini daha iyi anlamasını sağladı. Birkaç ay sonra kitap ödünç alma sayısı çok az değişmişti; buna karşılık ziyaretçilerin içeride geçirdiği süre artmıştı. Görevliler bu sonucu yalnız sayılarla değerlendirmedi. İnsanların oraya yeniden gelmek istemesini de önemli buldu. Yenilemenin asıl kazanımı daha çok kitap sergilemek değil, farklı insanların aynı yapıda kendilerine uygun bir yer bulabilmesiydi. Böylece mekânın başarısının yalnız kapasiteyle değil, kullanıcısıyla kurduğu ilişkiyle de ilgili olduğu anlaşıldı.",
    questions: [
      {prompt: "Parçanın bütününden çıkarılabilecek en kapsamlı yargı hangisidir?", options: ["Bir kamusal mekânın başarısı, yalnız kapasitesine değil farklı kullanıcı ihtiyaçlarına nasıl karşılık verdiğine de bağlıdır.", "Kütüphanelerde ödünç alınan kitap sayısı artmıyorsa yapılan yenilemenin başarılı sayılması mümkün değildir.", "Farklı kullanıcı gruplarının aynı mekânda bulunabilmesi için sessiz alanlardan vazgeçilmesi gerekir.", "Bir mekânı yenilerken kullanıcı görüşleri alınsa da son karar yalnız fiziksel kapasiteye göre verilmelidir."], answer: 0, explanation: "Metin, kapasitenin tek ölçüt olmadığını; farklı ihtiyaçlara karşılık veren düzenin ve kullanıcıyla kurulan ilişkinin de başarıyı belirlediğini vurguluyor.", type: "Ana düşünce"},
      {prompt: "Kitap ödünç alma sayısı çok az değişirken içeride geçirilen sürenin artması aşağıdakilerden hangisini özellikle destekler?", options: ["Yenilemenin kitaplara ilgiyi azalttığını.", "Kütüphanenin yalnız dinlenme alanına dönüştüğünü.", "Kullanıcı deneyimindeki iyileşmenin tek bir sayısal göstergeyle yakalanamayabileceğini.", "Ziyaretçilerin daha az kitap okuyup daha çok sohbet ettiğini."], answer: 2, explanation: "Ödünç alma sayısı tek başına sınırlı değişmiş olsa da kullanım süresinin artması, başarının birden fazla ölçütle değerlendirilmesi gerektiğini gösteriyor.", type: "Çıkarım"},
      {prompt: "Sessiz bölüm korunurken sohbet alanının ayrıca düzenlenmesi metinde hangi işlevi görür?", options: ["Bir grubun isteğinin diğerlerinden üstün tutulduğunu gösterir.", "Birbirinden farklı ihtiyaçların aynı yapıda sınırları belirlenerek birlikte karşılanabileceğini somutlaştırır.", "Kütüphanenin temel işlevinin kitaplardan sosyalleşmeye kaydığını kanıtlar.", "Başlangıçtaki gürültü kaygısının yersiz olduğunu daha uygulama yapılmadan gösterir."], answer: 1, explanation: "Alanların ayrılması, çatışabilecek ihtiyaçların birbirini dışlamadan karşılanmasına örnektir.", type: "Örnek işlevi"},
      {prompt: "Bu parçaya göre görevlilerin yaklaşımı için aşağıdakilerden hangisi söylenemez?", options: ["Karar öncesinde farklı kullanıcı gruplarını dinlemişlerdir.", "Yenilemenin etkisini yalnız ödünç alma sayısına indirgememişlerdir.", "Başlangıçtaki raf artırma fikrini kullanıcı görüşlerinden bağımsız biçimde uygulamışlardır.", "Mekânın yeniden tercih edilmesini de sonuçların bir parçası olarak görmüşlerdir."], answer: 2, explanation: "Tam tersine görevliler raf ekleme fikrini hemen uygulamak yerine kullanıcıları dinlemiştir.", type: "Çıkarılamayan yargı"},
      {prompt: "Parçanın düşünce akışı aşağıdakilerden hangisine en uygundur?", options: ["İlk çözüm önerisi → kullanıcı ihtiyaçlarının araştırılması → düzenlemenin uygulanması → sonuçların çok yönlü değerlendirilmesi", "Kullanıcı şikâyetleri → kütüphanenin kapatılması → yeni bina yapılması → kitap sayısının artırılması", "Sayısal verilerin toplanması → ziyaretçi görüşlerinin gereksiz bulunması → tek tip düzen kurulması → kullanımın azalması", "Gürültü sorununun belirlenmesi → sessiz bölümün kaldırılması → rafların artırılması → ziyaret süresinin sınırlandırılması"], answer: 0, explanation: "Metin önce ilk fikri, ardından ihtiyaçların dinlenmesini, uygulamayı ve sonuçların değerlendirilmesini anlatıyor.", type: "Paragraf yapısı"}
    ]
  },
  {
    id: "garden", title: "Bahçedeki küçük notlar", topic: "Gözlem ve öğrenme", difficulty: "medium",
    text: "Bir öğrenci grubu okul bahçesinde yetiştirdikleri bitkilerin neden farklı hızlarda büyüdüğünü merak etti. İlk tahminleri, büyük yapraklı bitkilerin her koşulda daha hızlı büyüyeceğiydi. Öğretmenleri bu tahmini hemen düzeltmek yerine gözlem defteri tutmalarını önerdi. Öğrenciler her hafta aynı gün bitkileri ölçtü; sulama miktarını ve saksıların bulunduğu yeri de kaydetti. Bir süre sonra pencereye yakın duran iki küçük bitkinin diğerlerinden daha hızlı geliştiğini fark ettiler. Yalnız yaprak büyüklüğüne bakarak karar vermenin yeterli olmadığını anladılar. Bunun üzerine yer ve su miktarını ayrı ayrı değiştiren yeni bir çalışma planladılar. İlk sonuçları kesin bir kural olarak sunmadılar; çünkü az sayıda bitki üzerinde çalışmışlardı. Yine de defterleri onlara önemli bir alışkanlık kazandırdı: Bekledikleri sonucu aramak yerine gördüklerini düzenli olarak yazmak. Dönem sonunda hazırladıkları sunumda en çok büyüyen bitkiyi değil, başlangıçtaki fikirlerinin nasıl değiştiğini anlattılar. Onlar için çalışmanın değeri doğru tahminde bulunmaktan çok, tahminlerini gözlemlerle yeniden değerlendirebilmekti.",
    questions: [
      {prompt: "Parçanın ana düşüncesi aşağıdakilerden hangisidir?", options: ["Bilimsel bir çalışmada doğru ilk tahmini yapmak, sonradan yapılan gözlemlerden daha değerlidir.", "Düzenli gözlem, kişinin başlangıçtaki beklentisini kanıtlamaktan çok gerektiğinde yeniden değerlendirmesine yardım eder.", "Bir deneyde çok sayıda değişkeni aynı anda değiştirmek sonuca daha hızlı ulaşmayı sağlar.", "Bitkilerin büyüme hızı esas olarak yapraklarının büyüklüğünden anlaşılabilir."], answer: 1, explanation: "Öğrencilerin asıl kazanımı, tahminlerini korumak değil gözlemler doğrultusunda değiştirebilmekti.", type: "Ana düşünce"},
      {prompt: "Öğretmenin öğrencilerin ilk tahminini hemen düzeltmeyip gözlem defteri önermesinden hangi sonuca ulaşılabilir?", options: ["Öğrencilerin yanlış bir düşünceyi kendi verileriyle sınamasını istemiştir.", "Büyük yapraklı bitkilerin gerçekten daha hızlı büyüdüğünü düşünmüştür.", "Ölçüm yapmadan önce sonucu kesinleştirmek istemiştir.", "Bitkilerin sulama miktarını önemsiz gördüğü için tartışmayı ertelemiştir."], answer: 0, explanation: "Öğretmen doğrudan doğru cevabı vermek yerine öğrencilerin kanıt toplayarak fikirlerini sınamasını sağlamıştır.", type: "Çıkarım"},
      {prompt: "Öğrencilerin ilk sonuçlarını kesin kural olarak sunmaması aşağıdaki tutumlardan hangisiyle daha çok ilişkilidir?", options: ["Sonuçları yalnız beklentiye uygun olduğunda kabul etme", "Sınırlı sayıdaki gözlemden genelleme yaparken temkinli olma", "Ölçümlerde yalnız en hızlı büyüyen bitkiyi dikkate alma", "Yeni veriler geldiğinde ilk görüşü değiştirmeyi reddetme"], answer: 1, explanation: "Az sayıda bitkiyle çalıştıkları için sonuçların genellenebilirliğini sınırlı görmüşlerdir.", type: "Bilimsel tutum"},
      {prompt: "Yer ve su miktarının ayrı ayrı değiştirilmesinin temel amacı nedir?", options: ["Bitkilerin hepsini aynı hızda büyütmek", "Gözlem defterine daha fazla veri yazmak", "Hangi etkenin değişimle ilişkili olduğunu daha açık biçimde ayırt etmek", "İlk tahmini farklı bir yoldan doğrulamak"], answer: 2, explanation: "Değişkenleri ayrı ayrı değiştirmek, her birinin olası etkisini daha sağlıklı değerlendirmeyi amaçlar.", type: "Yöntem"},
      {prompt: "“Bekledikleri sonucu aramak yerine gördüklerini düzenli olarak yazmak” sözüyle vurgulanan aşağıdakilerden hangisidir?", options: ["Veriyi beklentiye uydurmadan kaydetme", "Yalnız olumlu sonuçları seçme", "Tahmin yapmaktan tamamen vazgeçme", "Her gözlemi kesin bir kurala dönüştürme"], answer: 0, explanation: "Cümle, gözlemi beklentiye göre seçmek yerine veriyi olduğu gibi kaydetme alışkanlığını anlatıyor.", type: "Sözün anlamı"}
    ]
  },
  {
    id: "map", title: "Haritanın göstermediği", topic: "Kent ve deneyim", difficulty: "expert",
    text: "Bir şehir araştırmacısı aynı mahallenin iki haritasını hazırladı. İlk haritada yolların uzunluğu, duraklar ve binalar vardı. İkincisini ise mahallede yaşayanların anlattıklarından oluşturdu. Birinin kestirme saydığı dar sokak, bir başkası için karanlık olduğu için tercih edilmeyen bir yoldu. Haritada küçük görünen park, çocuklarıyla zaman geçiren aileler için mahallenin merkeziydi. Araştırmacı bu anlatıları teknik haritanın yerine koymadı; ikisini birlikte kullanmayı önerdi. Çünkü ölçüler fiziksel uzaklığı gösterirken insanların deneyimleri bir yerin nasıl algılandığını açıklıyordu. Belediyeye sunduğu raporda yalnız yeni yol açılmasını istemedi. Bazı sokakların aydınlatılmasını ve parktaki oturma alanlarının onarılmasını da önerdi. Bu öneriler büyük projeler kadar dikkat çekici değildi, fakat günlük yaşamda doğrudan karşılığı vardı. Araştırmacıya göre iyi bir plan, yalnız masada çizilen çizgilerden oluşamazdı. O çizgilerin üzerinde yürüyen insanların sesini de duymalıydı. Mahalle sakinleri raporu okuduklarında ilk kez kendi küçük deneyimlerinin kentle ilgili bir kararda yer bulduğunu hissetti.",
    questions: [
      {prompt: "Parçanın ana düşüncesi aşağıdakilerden hangisidir?", options: ["Kent planlamasında fiziksel ölçüler tek başına yeterlidir; kişisel deneyimler kararları gereksiz yere karmaşıklaştırır.", "İnsanların bir yeri nasıl deneyimlediği, teknik ölçümlerin yerine geçmeli ve sayısal veriler kullanılmamalıdır.", "Sağlıklı bir kent planı, teknik ölçülerle insanların günlük deneyimlerini birbirini tamamlayan bilgiler olarak değerlendirmelidir.", "Küçük ölçekli düzenlemeler yerine yalnız yeni yollar gibi büyük projelere öncelik verilmelidir."], answer: 2, explanation: "Araştırmacı iki tür bilgiden birini diğerinin yerine koymuyor; birlikte kullanılmalarını savunuyor.", type: "Ana düşünce"},
      {prompt: "Dar sokağın bir kişi için kestirme, başka biri için kaçınılan yol olması metinde neyi göstermektedir?", options: ["Fiziksel uzaklığın kişiden kişiye değiştiğini.", "Aynı fiziksel çevrenin güvenlik ve deneyim gibi etkenlerle farklı algılanabildiğini.", "Teknik haritaların yolların uzunluğunu yanlış ölçtüğünü.", "Karanlık sokakların her durumda daha uzun olduğunu."], answer: 1, explanation: "Örnek, aynı yolun ölçüsü değişmese de kişisel deneyim nedeniyle farklı değerlendirilebildiğini gösterir.", type: "Örnek işlevi"},
      {prompt: "Araştırmacının aydınlatma ve oturma alanı onarımı önermesi aşağıdakilerden hangisini destekler?", options: ["Günlük yaşamı etkileyen küçük düzenlemeler, büyük projeler kadar görünür olmasa da anlamlı olabilir.", "Teknik haritada yer almayan bütün alanların yeniden yapılması gerekir.", "Kent sorunlarının temel nedeni yeni yol açılmamasıdır.", "Mahalle sakinlerinin önerileri yalnız düşük maliyetliyse dikkate alınmalıdır."], answer: 0, explanation: "Metin bu önerilerin gösterişli olmadığını ama günlük yaşamda doğrudan karşılığı bulunduğunu söylüyor.", type: "Çıkarım"},
      {prompt: "Bu parçadan aşağıdakilerden hangisine ulaşılamaz?", options: ["Teknik veriler fiziksel çevrenin bazı özelliklerini göstermede yararlıdır.", "Mahalle sakinlerinin deneyimleri planlamada ek bir bilgi kaynağı olabilir.", "İnsan deneyimini dikkate almak teknik haritaları bütünüyle gereksiz kılar.", "Bir yerin algılanışı yalnız ölçülebilir uzaklıktan ibaret değildir."], answer: 2, explanation: "Araştırmacı teknik haritanın yerine deneyim haritasını koymuyor; ikisini birlikte kullanıyor.", type: "Çıkarılamayan yargı"},
      {prompt: "Araştırmacının “çizgilerin üzerinde yürüyen insanların sesini de duymak” gerektiğini söylemesiyle eleştirilen yaklaşım hangisidir?", options: ["Planı yalnız masa başındaki fiziksel verilere indirgemek", "Mahalle sakinlerinden birden fazla görüş almak", "Teknik ölçüleri insan deneyimiyle birlikte değerlendirmek", "Küçük iyileştirmelerin etkisini incelemek"], answer: 0, explanation: "İfade, planlamanın yalnız soyut çizim ve ölçülere dayanmasına karşı çıkıyor.", type: "Yazarın yaklaşımı"}
    ]
  },
  {
    id: "repair", title: "Bir eşyaya ikinci bakış", topic: "Üretim ve alışkanlık", difficulty: "medium",
    text: "Küçük bir tamir atölyesi, cumartesi günleri kapısını mahallenin gençlerine açmaya başladı. Amaç herkesi uzman bir tamirci yapmak değildi. Atölyenin sahibi, bozulan bir eşyanın hemen çöpe atılmadan önce incelenebileceğini göstermek istiyordu. İlk buluşmada çalışmayan bir masa lambası getirildi. Gençler sorunun büyük ve pahalı bir parçadan kaynaklandığını düşündü. Birlikte yapılan inceleme, gevşek bir bağlantının soruna yol açtığını ortaya çıkardı. Bu örnek her arızanın kolayca giderilebileceği anlamına gelmiyordu. Atölyede güvenlik gerektiren işlemler yalnız yetkili kişi tarafından yapılıyordu. Katılımcıların asıl görevi sorular sormak, parçaların işlevini anlamak ve süreci gözlemlemekti. Birkaç hafta sonra gençlerin anlattığı değişim, kaç eşya onardıklarından çok düşünme biçimleriyle ilgiliydi. Artık bir şey çalışmadığında önce nedenini merak ediyorlardı. Atölye sahibi bu merakı en önemli sonuç saydı. Çünkü bir nesnenin nasıl üretildiğini anlamak, hem emeğe verilen değeri artırıyor hem de yenisini alma kararını daha bilinçli hâle getiriyordu.",
    questions: [
      {prompt: "Parçanın ana düşüncesi aşağıdakilerden hangisidir?", options: ["Bir eşyanın nasıl çalıştığını sorgulamak, hem emeğe bakışı hem de tüketim kararlarını daha bilinçli hâle getirebilir.", "Bozulan her eşya, yeterince dikkatli incelenirse uzman yardımı olmadan kolayca onarılabilir.", "Tamir becerisi kazanmanın tek yolu arızalı ürünleri tek başına söküp yeniden kurmaktır.", "Yeni ürün almak yerine her koşulda eski ürünü kullanmaya devam etmek gerekir."], answer: 0, explanation: "Metin tamir becerisinden çok merak, üretimi anlama ve bilinçli karar verme üzerinde duruyor.", type: "Ana düşünce"},
      {prompt: "Masa lambasında beklenenden daha basit bir sorun bulunması metinde hangi düşünceyi desteklemek için kullanılmıştır?", options: ["İlk varsayımın inceleme yapılmadan doğru kabul edilmemesi gerektiğini.", "Bütün elektrik arızalarının gevşek bağlantıdan kaynaklandığını.", "Pahalı parçaların hiçbir zaman bozulmadığını.", "Gençlerin kısa sürede uzman tamirci olabildiğini."], answer: 0, explanation: "Gençlerin ilk tahmini büyük ve pahalı bir parçaydı; inceleme bunun yanlış olabileceğini gösterdi.", type: "Örnek işlevi"},
      {prompt: "Güvenlik gerektiren işlemlerin yalnız yetkili kişi tarafından yapılması bilgisi parçaya hangi sınırı getirir?", options: ["Merak etmenin öğrenmede değersiz olduğunu gösterir.", "İnceleme alışkanlığının, uzmanlık ve güvenlik gerektiren durumları yok saymak anlamına gelmediğini belirtir.", "Atölyenin gençlere hiçbir uygulama yaptırmadığını kanıtlar.", "Her arızanın tehlikeli olduğunu düşündürür."], answer: 1, explanation: "Metin sorgulamayı teşvik ederken güvenlik ve uzmanlık sınırını özellikle koruyor.", type: "Sınırlandırma"},
      {prompt: "Gençlerde birkaç hafta sonra görülen temel değişim aşağıdakilerden hangisidir?", options: ["Onardıkları eşya sayısını artırmayı tek başarı ölçütü saymaları", "Bir şey çalışmadığında doğrudan yenisini alma eğilimlerinin güçlenmesi", "Arızanın nedenini anlamaya yönelik soru sorma alışkanlığı geliştirmeleri", "Yetkili yardımına hiç ihtiyaç duymadıklarını düşünmeleri"], answer: 2, explanation: "Metin, değişimin onarım sayısından çok düşünme biçiminde ve nedenini merak etmede olduğunu söylüyor.", type: "Değişim"},
      {prompt: "Bu parçadan aşağıdaki yargılardan hangisi çıkarılamaz?", options: ["Bir nesnenin üretim sürecini anlamak emeğe verilen değeri artırabilir.", "Gözlem ve soru sorma da öğrenme sürecinin parçası olabilir.", "Bir eşyayı incelemek, yenisini alıp almama kararını daha bilinçli kılabilir.", "Tamir edilebilen bir eşyayı yenilemek her durumda yanlış ve gereksizdir."], answer: 3, explanation: "Metin bilinçli karar vermeyi savunuyor; yenisini almayı her koşulda yanlış ilan etmiyor.", type: "Çıkarılamayan yargı"}
    ]
  },
  {
    id: "workshop", title: "Bir fikrin ilk hâli", topic: "Üretim ve geri bildirim", difficulty: "hard",
    text: "Bir tasarım kulübü, okul koridorunda kullanılacak yönlendirme levhaları hazırlamak için çalışmaya başladı. İlk toplantıda herkes en iyi fikrini doğrudan son tasarıma dönüştürmek istiyordu. Kulüp danışmanı ise önce küçük kâğıt örnekler hazırlanmasını ve öğrencilerin bu örnekleri koridorda denemesini önerdi. Denemelerde bazı yazıların uzaktan okunmadığı, bazı okların da iki farklı yöne işaret ediyormuş gibi algılandığı görüldü. Tasarımcı öğrenciler başlangıçta bunu başarısızlık saydı. Fakat birkaç tur sonra küçük hataları erken fark etmenin büyük bir levhayı yeniden üretmekten daha kolay olduğunu anladılar. Son sürüm, ilk çizimlerden hiçbirine tam olarak benzemiyordu; farklı fikirlerin işe yarayan tarafları bir araya gelmişti. Kulüp için önemli olan, ilk fikri savunmak değil, kullanım sırasında ortaya çıkan sorunları görüp tasarımı değiştirebilmekti. Böylece deneme, sonucun önündeki bir engel değil, sonuca ulaşmanın bir parçası hâline geldi.",
    questions: [
      {prompt: "Parçanın ana düşüncesi aşağıdakilerden hangisidir?", options: ["Bir tasarımın gelişmesi, ilk fikri korumaktan çok gerçek kullanımda ortaya çıkan sorunlara göre yeniden biçimlendirilmesine bağlıdır.", "Başarılı bir tasarımın en önemli özelliği, ilk çizimin hiç değiştirilmeden uygulanmasıdır.", "Bir ekip çalışmasında farklı fikirleri birleştirmek tasarımın tutarlılığını mutlaka bozar.", "Küçük örneklerle yapılan denemeler yalnız zaman kaybını artırdığı için son ürün doğrudan üretilmelidir."], answer: 0, explanation: "Metin deneme, geri bildirim ve değişiklik yapabilmeyi tasarım sürecinin temel parçası olarak sunuyor.", type: "Ana düşünce"},
      {prompt: "Öğrencilerin küçük örneklerde bulunan hataları başlangıçta “başarısızlık” sayıp sonra yararlı görmesi neyi gösterir?", options: ["Başarısızlık kavramına ilişkin değerlendirmelerinin süreç içinde değiştiğini.", "Koridordaki kullanıcıların tasarıma hiç etkisi olmadığını.", "Son tasarımın ilk örneklerden daha az anlaşılır olduğunu.", "Danışmanın ilk önerisinden vazgeçtiğini."], answer: 0, explanation: "Deneme sonucu bulunan hatalar önce başarısızlık, sonra erken geri bildirim fırsatı olarak görülmüştür.", type: "Tutum değişimi"},
      {prompt: "Son sürümün ilk çizimlerden hiçbirine tam olarak benzememesi aşağıdakilerden hangisinin göstergesidir?", options: ["Projenin başlangıç hedefinden tamamen vazgeçildiğinin.", "Farklı fikirlerin işe yarayan yönlerinin denemeler sonucunda yeni bir çözümde birleştiğinin.", "Öğrencilerin ilk çizimleri hatırlamadığının.", "Danışmanın bütün tasarım kararlarını tek başına verdiğinin."], answer: 1, explanation: "Metin son sürümün farklı fikirlerin işe yarayan taraflarını bir araya getirdiğini açıkça belirtiyor.", type: "Çıkarım"},
      {prompt: "Danışmanın kâğıt örnekleri doğrudan koridorda denetmek istemesi hangi ilkeye dayanır?", options: ["Bir tasarımın yalnız görünüşüne bakılarak değerlendirilmesi gerektiğine.", "Kullanım bağlamında ortaya çıkan sorunların masa başında fark edilmeyebileceğine.", "Büyük üretimin küçük örneklerden her zaman daha ucuz olduğuna.", "İlk fikrin kullanıcı geri bildiriminden korunması gerektiğine."], answer: 1, explanation: "Gerçek kullanım ortamındaki okunabilirlik ve yön algısı sorunları ancak denemede görünür hâle gelmiştir.", type: "Yöntem"},
      {prompt: "Parçanın düşünce akışı aşağıdakilerden hangisine en uygundur?", options: ["İlk fikre bağlılık → küçük ölçekli deneme → sorunların görülmesi → tasarımın geri bildirimle geliştirilmesi", "Sorunun yok sayılması → son ürünün üretilmesi → kullanıcıların dışlanması → ilk çizime geri dönülmesi", "Farklı fikirlerin elenmesi → tek tasarımcının seçilmesi → denemeden vazgeçilmesi → ürünün küçültülmesi", "Koridorun değiştirilmesi → levhaların gereksiz bulunması → tasarım kulübünün kapanması → yeni proje seçilmesi"], answer: 0, explanation: "Metin ilk fikri hemen sonuca dönüştürme isteğinden deneme ve iterasyon anlayışına geçişi anlatıyor.", type: "Paragraf yapısı"}
    ]
  },
  {
    id: "queue", title: "Sıranın görünmeyen kısmı", topic: "Sistem ve davranış", difficulty: "hard",
    text: "Bir okul kantininde öğle arasında oluşan uzun kuyruklar için ilk çözüm, kasaya ikinci bir görevli eklemek oldu. Kuyruk biraz kısaldı ancak yoğunluk tamamen ortadan kalkmadı. Öğrenci meclisi birkaç gün boyunca sıranın nasıl ilerlediğini gözlemledi. Asıl yavaşlamanın ödeme sırasında değil, öğrencilerin kasaya geldiklerinde ne alacaklarına karar vermeye çalışmalarından kaynaklandığını fark ettiler. Bunun üzerine ürünlerin listesi ve fiyatları sıranın başladığı noktaya taşındı. Ayrıca en sık alınan birkaç ürün için küçük hazır paketler oluşturuldu. Bir hafta sonra kasadaki görevli sayısı değişmediği hâlde bekleme süresi azaldı. Bu durum, bir sorunun görünen noktasına müdahale etmenin her zaman yeterli olmadığını gösterdi. Bazen gecikmenin nedeni sistemin daha önceki bir aşamasında bulunabilir. Öğrenci meclisi sonraki çalışmalarında çözüm önermeden önce sürecin tamamını izlemeyi alışkanlık hâline getirdi.",
    questions: [
      {prompt: "İkinci görevlinin eklenmesi kuyruğu yalnız kısmen azaltmıştır çünkü aşağıdakilerden hangisi gözden kaçmıştır?", options: ["Yoğunluğun önemli bir bölümünün ödeme anından önce, öğrencilerin seçim yaparken oluşması.", "Kantin çalışanlarının ürünlerin fiyatlarını bilmemesi.", "Öğrencilerin ödeme yapmak istememesi.", "Hazır paketlerin kasada daha yavaş satılması."], answer: 0, explanation: "Asıl darboğazın ödeme değil karar verme aşamasında olduğu sonradan gözlemlenmiştir.", type: "Neden-sonuç"},
      {prompt: "Ürün listesi ile fiyatların sıranın başlangıcına taşınmasının temel etkisi aşağıdakilerden hangisidir?", options: ["Karar verme sürecinin kasaya gelmeden önce başlamasını sağlamak.", "Öğrencilerin daha pahalı ürünleri seçmesini teşvik etmek.", "Kasadaki görevli sayısını görünürde artırmak.", "Kantinin ürün çeşidini azaltmak."], answer: 0, explanation: "Bilgi daha erken sunulunca öğrenciler kasaya gelmeden seçimini yapabilir ve ödeme aşamasındaki bekleme azalır.", type: "Süreç analizi"},
      {prompt: "Bu parçanın ana düşüncesi aşağıdakilerden hangisidir?", options: ["Bir sorunun görüldüğü noktaya müdahale etmek yerine, sürecin tamamını inceleyerek gerçek darboğazı bulmak daha etkili olabilir.", "Kuyruk sorunlarının en güvenilir çözümü her zaman çalışan sayısını artırmaktır.", "Hazır paket sistemi bütün kantinlerde tek başına yeterli bir çözümdür.", "Bir süreçte gecikme varsa bunun nedeni mutlaka son aşamadadır."], answer: 0, explanation: "Metin görünen sorun noktasıyla gerçek nedenin farklı olabileceğini vurguluyor.", type: "Ana düşünce"},
      {prompt: "Öğrenci meclisi yalnız ödeme süresini ölçmekle yetinseydi aşağıdakilerden hangisini fark etme olasılığı azalırdı?", options: ["Karar verme aşamasındaki gecikmenin kuyruğa katkısını.", "Kasada iki görevli bulunduğunu.", "Öğle arasında kantinin açık olduğunu.", "Ürünlerin bir fiyatı bulunduğunu."], answer: 0, explanation: "Sürecin tamamı gözlenmese karar verme aşamasındaki bekleme görünmez kalabilirdi.", type: "Çıkarım"},
      {prompt: "“Sorunun görünen noktasına müdahale etmek her zaman yeterli değildir.” cümlesi metinde hangi amaçla kullanılmıştır?", options: ["İkinci görevli ekleme çözümünün neden sınırlı kaldığını genelleştiren bir ilkeye bağlamak.", "Kantinde hiçbir değişiklik yapılmaması gerektiğini savunmak.", "Öğrenci meclisinin gözlem yapmasını gereksiz göstermek.", "Bekleme süresinin tamamen ortadan kalktığını açıklamak."], answer: 0, explanation: "Bu cümle somut kantin örneğinden daha genel bir süreç iyileştirme ilkesine geçiş yapıyor.", type: "Sözün işlevi"}
    ]
  },
  {
    id: "archive", title: "Eski fotoğrafların düzeni", topic: "Bilgi ve sınıflandırma", difficulty: "hard",
    text: "Bir yerel tarih grubu, mahalle sakinlerinden topladığı eski fotoğrafları dijital ortama aktarmaya başladı. İlk günlerde dosyalar yalnız çekildikleri tahmin edilen yıllara göre sıralandı. Fakat kısa süre sonra aynı meydanın farklı dönemlerini ya da aynı ailenin farklı sokaklardaki yaşamını bulmak zorlaştı. Gruptaki bir öğrenci, her fotoğrafa yer, kişi, tarih aralığı ve olay gibi birden fazla etiket eklemeyi önerdi. Bu yöntem başta daha fazla iş gibi görünüyordu. Buna karşılık arşiv büyüdükçe tek bir fotoğrafın farklı sorulara cevap verebilmesini sağladı. Bir araştırmacı aynı sokağın zaman içindeki değişimini, başka biri ise mahalledeki dükkânların geçmişini kolayca izleyebildi. Grup, sınıflandırmanın yalnız düzen sağlamak için değil, daha önce kurulmamış ilişkileri görünür kılmak için de önemli olduğunu fark etti. Arşivin değeri fotoğraf sayısından çok, o fotoğraflar arasında anlamlı yollar kurulabilmesiyle arttı.",
    questions: [
      {prompt: "Parçanın ana düşüncesi aşağıdakilerden hangisidir?", options: ["İyi bir sınıflandırma, yalnız düzen sağlamakla kalmaz; bilgiler arasında farklı sorulara göre yeni ilişkiler kurulmasını da kolaylaştırır.", "Dijital arşivlerde en güvenilir yöntem bütün dosyaları yalnız tarihe göre sıralamaktır.", "Bir arşivin değeri esas olarak içerdiği fotoğraf sayısının çokluğuna bağlıdır.", "Bir fotoğrafa birden fazla etiket vermek bilgiye ulaşmayı zorlaştırdığı için mümkün olduğunca kaçınılmalıdır."], answer: 0, explanation: "Metin, sınıflandırmanın düzenin ötesinde farklı bağlantıları görünür kıldığını vurguluyor.", type: "Ana düşünce"},
      {prompt: "Fotoğrafları yalnız tahmini yıllara göre sıralamanın yetersiz kalmasının temel nedeni nedir?", options: ["Fotoğrafların tarihlerini tahmin etmenin her zaman imkânsız olması.", "Aynı malzemeye yer, kişi ya da olay gibi farklı araştırma sorularından ulaşmayı zorlaştırması.", "Dijital dosyaların kronolojik sırayı desteklememesi.", "Mahalle sakinlerinin tarih bilgisi vermeyi reddetmesi."], answer: 1, explanation: "Tek boyutlu tarih sırası, aynı fotoğrafa farklı ilişkiler üzerinden erişimi sınırlıyordu.", type: "Neden-sonuç"},
      {prompt: "Birden fazla etiket ekleme yöntemiyle ilgili aşağıdakilerden hangisi söylenebilir?", options: ["Başlangıçta ek emek gerektirse de arşiv büyüdükçe farklı araştırma yolları oluşturmuştur.", "Fotoğraf sayısını azaltarak arşivin daha küçük tutulmasını sağlamıştır.", "Tarih bilgisini tamamen gereksiz hâle getirmiştir.", "Yalnız aynı aileye ait fotoğrafları bulmayı kolaylaştırmıştır."], answer: 0, explanation: "Etiketleme başta daha fazla iş görünmüş, fakat büyüyen arşivde farklı sorulara cevap vermeyi kolaylaştırmıştır.", type: "Çıkarım"},
      {prompt: "“Bu yöntem başta daha fazla iş gibi görünüyordu.” cümlesinin parçadaki işlevi nedir?", options: ["Yöntemin kısa vadeli maliyeti ile uzun vadeli yararı arasında karşıtlık kurmak.", "Etiketleme yönteminin başarısız olduğunu kanıtlamak.", "Grubun dijitalleştirmeden vazgeçtiğini göstermek.", "Fotoğrafların tarih sırasının yeterli olduğunu savunmak."], answer: 0, explanation: "Cümle, ilk zahmet ile sonradan ortaya çıkan erişim avantajını karşılaştırmaya zemin hazırlıyor.", type: "Sözün işlevi"},
      {prompt: "Bu parçadan aşağıdaki yargılardan hangisine ulaşılabilir?", options: ["Bilginin nasıl sınıflandırıldığı, o bilgiden hangi ilişkilerin görülebileceğini etkileyebilir.", "Bir arşiv büyüdükçe sınıflandırma yapmak gereksizleşir.", "Her araştırmacı arşivde yalnız tek bir tür ilişki arar.", "Dijital arşivlerde fotoğrafların içeriği değil yalnız dosya adları önemlidir."], answer: 0, explanation: "Farklı etiketler aynı fotoğrafın farklı sorularla ilişkilendirilebilmesini sağlamıştır.", type: "Çıkarım"}
    ]
  },
  {
    id: "bench", title: "Parktaki bankın yeri", topic: "Gözlem ve karar", difficulty: "medium",
    text: "Bir belediye ekibi küçük bir parkı yenilerken yeni bankların en güzel manzarayı gören tepeye yerleştirilmesini planladı. Çizim üzerinde bu seçim oldukça mantıklı görünüyordu. Ancak ekip, uygulamadan önce birkaç gün parkı kullananları izlemeye karar verdi. Sabah saatlerinde yaşlıların düz yoldaki gölgeli alanlarda dinlendiği, öğleden sonra çocuklarını bekleyen yetişkinlerin oyun alanına yakın yerleri tercih ettiği görüldü. Tepe ise manzarası güzel olmasına rağmen dik yolu nedeniyle daha az kullanılıyordu. Bunun üzerine bankların tamamını tek noktaya koymak yerine farklı ihtiyaçlara göre birkaç bölgeye dağıttılar. Yenilemeden sonra tepedeki banklar yine kullanıldı fakat en yoğun kullanım düz ve gölgeli alanda gerçekleşti. Ekip, iyi bir kararın yalnız haritada çekici görünen noktayı seçmek olmadığını anladı. Bir alanın nasıl kullanılacağını kestirebilmek için insanların günlük hareketlerini de hesaba katmak gerekiyordu.",
    questions: [
      {prompt: "Parçanın ana düşüncesi aşağıdakilerden hangisidir?", options: ["Bir mekânla ilgili karar verirken yalnız çizim üzerindeki çekiciliğe değil, insanların o alanı gerçekte nasıl kullandığına da bakmak gerekir.", "Parklarda en iyi bank konumu her zaman en güzel manzarayı gören noktadır.", "Kullanıcı davranışı gözlemlense bile ilk tasarım kararları değiştirilmemelidir.", "Bir parkta farklı kullanıcı grupları için ayrı bölgeler oluşturmak mekânın kullanımını mutlaka azaltır."], answer: 0, explanation: "Metin, soyut planla gerçek kullanım arasındaki farkı gözlemle düzeltmeyi vurguluyor.", type: "Ana düşünce"},
      {prompt: "Tepe manzarası güzel olduğu hâlde daha az kullanılmıştır. Bu durum aşağıdakilerden hangisini gösterir?", options: ["Bir mekânın tercih edilmesinde estetik çekiciliğin yanında erişilebilirlik gibi etkenlerin de önemli olabileceğini.", "İnsanların manzaralı alanlardan genel olarak hoşlanmadığını.", "Bankların tepeye konmasının parkı kullanılamaz hâle getirdiğini.", "Gölgeli alanların her kullanıcı grubu için tek doğru seçenek olduğunu."], answer: 0, explanation: "Dik yol, güzel manzaraya rağmen tepenin kullanımını sınırlamıştır; erişim tercihi etkileyen başka bir etkendir.", type: "Çıkarım"},
      {prompt: "Ekip neden bankların tamamını tek bir noktada toplamak yerine farklı bölgelere dağıtmıştır?", options: ["Farklı kullanıcıların günün farklı zamanlarında farklı alanları tercih ettiğini gözlemledikleri için.", "Tepedeki manzarayı tamamen kapatmak istedikleri için.", "Parkın çizim planını uygulamaktan vazgeçtikleri için.", "Bankların sayısını azaltmak zorunda kaldıkları için."], answer: 0, explanation: "Gözlem, yaşlılar ve çocuk bekleyen yetişkinler gibi grupların farklı ihtiyaç ve güzergâhlara sahip olduğunu göstermiştir.", type: "Neden-sonuç"},
      {prompt: "“Çizim üzerinde bu seçim oldukça mantıklı görünüyordu.” cümlesi metinde hangi amaçla kullanılmıştır?", options: ["Kâğıt üzerindeki varsayımla gerçek kullanım arasındaki farkı hazırlamak.", "İlk planın en doğru çözüm olduğunu kanıtlamak.", "Gözlem yapmanın gereksiz olduğunu göstermek.", "Parkın manzarasının değiştiğini açıklamak."], answer: 0, explanation: "Cümle, daha sonra gözlemle ortaya çıkan farklı kullanıcı davranışıyla karşılaştırılmak üzere ilk varsayımı kuruyor.", type: "Sözün işlevi"},
      {prompt: "Bu parçadan aşağıdakilerden hangisine ulaşılamaz?", options: ["Kullanıcı gözlemi, tasarım kararlarının yeniden değerlendirilmesine yol açabilir.", "Aynı park içindeki farklı bölgeler farklı kullanıcı ihtiyaçlarına karşılık verebilir.", "En yoğun kullanılan alanın her durumda görsel olarak en çekici alan olması gerekir.", "Erişim biçimi, bir alanın ne kadar kullanıldığını etkileyebilir."], answer: 2, explanation: "Metin tam tersine, en güzel manzaralı alanın en yoğun kullanılan alan olmadığını gösteriyor.", type: "Çıkarılamayan yargı"}
    ]
  },
  {
    id: "museum", title: "Etiketin söylediği kadar", topic: "Bilgi ve yorum", difficulty: "expert",
    text: "Bir müze, yeni sergisinde eserlerin yanındaki açıklama metinlerini kısaltmayı planladı. İlk taslakta her nesnenin tarihi, malzemesi ve üretildiği yer tek paragrafta veriliyordu. Ziyaretçi gözlemleri ise başka bir sorunu ortaya çıkardı: İnsanlar bilgiyi okuyordu ama nesneler arasındaki ilişkiyi kurmakta zorlanıyordu. Ekip bunun üzerine bazı etiketleri kısaltırken, yan yana duran iki eser için ortak bir soru ekledi: “Bu iki nesnenin kullanım amacı neden farklılaşmış olabilir?” Yeni düzen bilgiyi azaltmak için değil, ziyaretçinin karşılaştırma yapmasına alan açmak için tasarlandı. Bir ay sonra bütün ziyaretçilerin etiketleri sonuna kadar okuduğu söylenemezdi; ancak rehberler, eserler hakkında sorulan soruların daha çok karşılaştırma ve neden-sonuç içermeye başladığını fark etti. Müze ekibi bu sonucu, daha fazla bilgi vermekle daha iyi öğrenme sağlamak arasında doğrudan bir eşitlik olmadığının işareti saydı. Onlara göre iyi bir açıklama, yalnız cevap vermemeli; bakılan nesne hakkında yeni ve anlamlı bir soru da doğurabilmeliydi.",
    questions: [
      {prompt: "Parçanın ana düşüncesi aşağıdakilerden hangisidir?", options: ["Bir açıklamanın niteliği yalnız içerdiği bilgi miktarıyla değil, ziyaretçiyi ilişki kurmaya ve düşünmeye yöneltmesiyle de değerlendirilmelidir.", "Müze etiketleri olabildiğince kısa tutulmalı ve yalnız tarih bilgisi vermelidir.", "Ziyaretçiler uzun metinleri okumadığı için eserler hakkında hiçbir açıklama kullanılmamalıdır.", "Karşılaştırma soruları ancak rehber eşliğindeki ziyaretlerde işe yarar."], answer: 0, explanation: "Metin, daha fazla bilgi ile daha iyi öğrenmenin aynı şey olmadığını; iyi açıklamanın düşünme ve soru üretme işlevini vurguluyor.", type: "Ana düşünce"},
      {prompt: "Ortak karşılaştırma sorusunun eklenmesindeki temel amaç nedir?", options: ["Ziyaretçinin iki eser arasında ilişki kurmasını teşvik etmek.", "Eserlere ait tarih ve malzeme bilgisini tamamen kaldırmak.", "Bütün ziyaretçilerin etiketi sonuna kadar okumasını zorunlu kılmak.", "Rehberlerin sergideki rolünü azaltmak."], answer: 0, explanation: "Soru, bilgi yükünü artırmaktan çok ziyaretçinin karşılaştırma yapmasına alan açmak için eklenmiştir.", type: "Amaç"},
      {prompt: "Etiketlerin tamamının herkes tarafından okunmamasına rağmen ekibin yeni düzeni anlamlı bulmasının nedeni nedir?", options: ["Ziyaretçilerin sorduğu soruların daha ilişkisel ve neden-sonuç odaklı hâle gelmesi.", "Sergideki eser sayısının artırılması.", "Bütün tarih bilgilerinin kaldırılması.", "Ziyaret süresinin kesin olarak iki katına çıkması."], answer: 0, explanation: "Ekip başarıyı yalnız okunan metin miktarıyla değil, soruların niteliğindeki değişimle de değerlendirmiştir.", type: "Çıkarım"},
      {prompt: "Bu parçadan aşağıdakilerden hangisine ulaşılamaz?", options: ["Bilgi sunma biçimi, ziyaretçinin nasıl düşündüğünü etkileyebilir.", "Kısa metin her durumda uzun metinden daha öğreticidir.", "Öğrenme çıktısı yalnız okunan kelime sayısıyla ölçülemeyebilir.", "Bir soru, nesneler arasında ilişki kurmaya yardımcı olabilir."], answer: 1, explanation: "Metin kısalığı tek başına üstün ilan etmiyor; asıl vurgu düzenleme ve düşünmeyi destekleyen sorular üzerinde.", type: "Çıkarılamayan yargı"},
      {prompt: "Parçada gözlem verilerinin kullanılma biçimi aşağıdakilerden hangisine örnektir?", options: ["İlk tasarımı gerçek kullanıcı davranışına göre yeniden düzenlemeye.", "Ziyaretçi görüşlerini dikkate almadan bilgi miktarını artırmaya.", "Yalnız rehberlerin tercihine göre karar vermeye.", "Serginin başarısını tek bir sayısal ölçüte indirmeye."], answer: 0, explanation: "İlk taslak, ziyaretçilerin ilişki kurmakta zorlandığı gözlemlenince değiştirilmiştir.", type: "Yöntem"}
    ]
  },
  {
    id: "studyroom", title: "Sessizliğin tek ölçüsü", topic: "Çalışma ortamı ve veri", difficulty: "expert",
    text: "Bir okul, etüt salonlarının verimini artırmak için en sessiz odayı “örnek çalışma alanı” ilan etmeyi düşündü. Yönetim önce yalnız desibel ölçümlerine baktı ve bodrum kattaki küçük salonun açık ara en sessiz yer olduğunu gördü. Ancak öğrencilerle yapılan kısa görüşmeler farklı bir tablo ortaya koydu. Bazıları odayı havasız buluyor, bazıları da pencere olmadığı için uzun süre odaklanamadığını söylüyordu. Üst kattaki salon biraz daha gürültülüydü fakat gün ışığı alıyor, masalar arasında daha fazla boşluk bulunuyordu. Yönetim bir hafta boyunca yalnız ses düzeyini değil, öğrencilerin salonda kalma sürelerini ve tekrar gelme oranlarını da izledi. Sonuçta en sessiz oda en uzun kullanılan oda değildi. Bunun üzerine tek bir “en iyi salon” seçmek yerine farklı çalışma tercihlerine göre iki alanı da iyileştirmeye karar verdiler. Bu deneyim onlara ölçüm yapmanın gereksiz olmadığını, fakat hangi ölçünün gerçekten amaçla ilişkili olduğunun ayrıca düşünülmesi gerektiğini gösterdi.",
    questions: [
      {prompt: "Parçanın ana düşüncesi aşağıdakilerden hangisidir?", options: ["Bir ortamı değerlendirirken tek bir ölçüte güvenmek yerine, amaca ilişkin birden fazla göstergeyi ve kullanıcı deneyimini birlikte düşünmek gerekir.", "Çalışma salonlarında sessizlik, diğer bütün çevresel özelliklerden daha önemlidir.", "Öğrenci görüşleri sayısal ölçümlerin yerini tamamen almalıdır.", "En iyi çalışma alanı her zaman gün ışığı alan en büyük odadır."], answer: 0, explanation: "Metin ölçümü reddetmiyor; hangi ölçütün amaçla ilgili olduğunun ve başka göstergelerle birlikte ele alınmasının önemini vurguluyor.", type: "Ana düşünce"},
      {prompt: "Bodrum kattaki salonun en sessiz olmasına rağmen en uzun kullanılan salon olmaması neyi gösterir?", options: ["Sessizliğin çalışma ortamı tercihlerini açıklayan tek değişken olmadığını.", "Desibel ölçümlerinin yanlış yapıldığını.", "Öğrencilerin sessiz ortamlarda çalışamadığını.", "Gün ışığının bütün öğrenciler için zorunlu olduğunu."], answer: 0, explanation: "Havasızlık, pencere ve mekânsal rahatlık gibi başka etkenler de kullanım tercihini etkilemiştir.", type: "Çıkarım"},
      {prompt: "Yönetimin kalma süresi ve tekrar gelme oranını da izlemesi hangi değişimi gösterir?", options: ["Başarı ölçütünü yalnız fiziksel sessizlikten kullanım davranışını da kapsayacak biçimde genişlettiğini.", "Ses ölçümlerini tamamen bıraktığını.", "Öğrencilerin görüşlerini önemsiz bulduğunu.", "Bodrum salonunu kapatma kararı aldığını."], answer: 0, explanation: "Yönetim tek ölçütten çoklu göstergelere geçmiştir.", type: "Yöntem"},
      {prompt: "Bu parçadan aşağıdakilerden hangisine ulaşılamaz?", options: ["Bir ölçüm doğru olsa bile, amaç açısından tek başına yeterli olmayabilir.", "Farklı öğrencilerin çalışma ortamı tercihleri birbirinden ayrılabilir.", "En sessiz salonun herkes için en verimli salon olduğu kesinleşmiştir.", "Kullanım davranışı, ortam değerlendirmesinde ek bir veri sağlayabilir."], answer: 2, explanation: "Metin tam tersine en sessiz salonun en uzun kullanılan salon olmadığını belirtir.", type: "Çıkarılamayan yargı"},
      {prompt: "Son cümlede “hangi ölçünün gerçekten amaçla ilişkili olduğunun düşünülmesi” sözüyle vurgulanan nedir?", options: ["Veri toplamak kadar, seçilen göstergenin değerlendirilmek istenen hedefi temsil edip etmediğinin de sorgulanması.", "Sayısal ölçümlerin her koşulda terk edilmesi.", "Öğrencilerin bütün kararları tek başına vermesi.", "Yalnız tekrar gelme oranının kullanılmasının yeterli olması."], answer: 0, explanation: "Metin, ölçmenin kendisinden çok doğru ölçütü seçmenin önemine dikkat çekiyor.", type: "Sözün anlamı"}
    ]
  }
];
export const EXERCISES = [
  {id: "groups", title: "Kelime grupları", description: "Üç kelimelik grupları rahat bir ritimle takip et."},
  {id: "lines", title: "Satır takibi", description: "Vurgulanan satırı izle; anlam koparsa duraklat."},
  {id: "focus", title: "Odak noktası", description: "Merkez sözcüğe bakarken yan sözcükleri de fark et."},
  {id: "returns", title: "Tek geçiş", description: "Önceki grup gizlenirken ana fikri aklında tut."},
  {id: "paragraph", title: "Kısa paragraf", description: "Metni kendi hızında oku; bitince anlama sorusunu yanıtla."}
];
